<s>
<0695311>_NULL <h>_NULL How_RRQ to_II Work_NN1 With_IW Municipalities_NN2 to_TO Save_VV0 Community_NN1 Cats_NN2 <p>_NULL 
</s>
<s>
By_II Rick_NP1 DuCharme_NP1 ,_, Founder_NN1 and_CC Director_NN1 of_IO First_MD Coast_NN1 No_AT More_RGR Homeless_JJ Pets_NN2 ,_, August_NPM1 2012_MC <p>_NULL 
</s>
<s>
If_CS saving_VVG the_AT lives_NN2 of_IO your_APPGE community_NN1 's_GE cats_NN2 is_VBZ your_APPGE goal_NN1 ,_, you_PPY 'll_VM probably_RR find_VVI yourself_PPX1 having_VHG to_TO work_VVI with_IW a_AT1 government_NN1 agency_NN1 at_II some_DD point_NN1 ._. 
</s>
<s>
It_PPH1 could_VM be_VBI the_AT most_RGT important_JJ relationship_NN1 you_PPY ever_RR invest_VV0 in_RP ._. <p>_NULL 
</s>
<s>
The_AT government_NN1 is_VBZ a_AT1 big_JJ part_NN1 of_IO our_APPGE lives_NN2 ,_, whether_CSW we_PPIS2 like_VV0 it_PPH1 or_CC not_XX ,_, and_CC in_II most_DAT areas_NN2 they_PPHS2 are_VBR a_AT1 big_JJ part_NN1 of_IO animal_NN1 welfare_NN1 ._. 
</s>
<s>
The_AT government_NN1 is_VBZ often_RR the_AT most_RGT financially_RR invested_VVN animal_NN1 welfare_NN1 shareholder_NN1 in_II a_AT1 community_NN1 ,_, either_RR through_II directly_RR operating_VVG animal_NN1 control_NN1 or_CC through_II an_AT1 animal_NN1 control_NN1 contract_NN1 with_IW a_AT1 private_JJ organization_NN1 ._. 
</s>
<s>
(_( I_PPIS1 use_VV0 the_AT term_NN1 "_" shareholder_NN1 "_" rather_II21 than_II22 "_" stakeholder_NN1 "_" because_CS the_AT groups_NN2 we_PPIS2 are_VBR interested_JJ in_II working_VVG with_IW are_VBR those_DD2 that_CST have_VH0 invested_VVN in_II animal_NN1 welfare_NN1 ,_, not_XX just_RR those_DD2 that_CST are_VBR affected_VVN by_II ,_, or_CC have_VH0 an_AT1 interest_NN1 in_RP ,_, animal_NN1 welfare_NN1 ._. )_) <p>_NULL 
</s>
<s>
The_AT fact_NN1 is_VBZ that_CST if_CS municipal_JJ or_CC contracted_VVD private_JJ animal_NN1 shelters_NN2 are_VBR where_CS the_AT cats_NN2 are_VBR dying_VVG ,_, then_RT you_PPY must_VM work_VVI with_IW the_AT shelter_NN1 if_CS you_PPY want_VV0 to_TO save_VVI their_APPGE lives_NN2 ._. <p>_NULL 
</s>
<s>
Relationship_NN1 Building_NN1 <p>_NULL 
</s>
<s>
The_AT relationships_NN2 that_CST a_AT1 group_NN1 builds_VVZ are_VBR assets_NN2 of_IO that_DD1 organization_NN1 to_TO be_VBI used_VVN in_II the_AT pursuit_NN1 of_IO their_APPGE mission_NN1 ._. 
</s>
<s>
There_EX are_VBR many_DA2 levels_NN2 of_IO the_AT government_NN1 to_TO work_VVI with_IW ,_, and_CC each_DD1 of_IO those_DD2 levels_NN2 requires_VVZ different_JJ skills_NN2 and_CC tactics_NN2 ._. <p>_NULL 
</s>
<s>
In_II Jacksonville_NP1 ,_, FL_NNU ,_, where_CS I_PPIS1 work_VV0 for_IF First_MD Coast_NN1 No_AT More_RGR Homeless_JJ Pets_NN2 (_( FCNMHP_NP1 )_) ,_, we_PPIS2 deal_VV0 with_IW the_AT government_NN1 on_II a_AT1 number_NN1 of_IO levels_NN2 :_: <p>_NULL 
</s>
<s>
These_DD2 are_VBR just_RR the_AT people_NN in_II government_NN1 who_PNQS are_VBR directly_RR involved_JJ in_II animal_NN1 welfare_NN1 ._. 
</s>
<s>
In_II Jacksonville_NP1 ,_, we_PPIS2 have_VH0 a_AT1 consolidated_JJ city/county_NN1 government_NN1 ;_; in_II other_JJ areas_NN2 of_IO the_AT country_NN1 ,_, there_EX is_VBZ often_RR the_AT same_DA or_CC a_AT1 similar_JJ bureaucracy_NN1 duplicated_VVD at_II both_RR city_NN1 and_CC county_NN1 levels_NN2 ,_, both_DB2 of_IO which_DDQ might_VM operate_VVI shelters_NN2 or_CC animal_NN1 control_NN1 services_NN2 ._. 
</s>
<s>
If_CS there_EX is_VBZ a_AT1 non-profit_JJ organization_NN1 that_CST is_VBZ running_VVG the_AT shelter_NN1 under_II contract_NN1 with_IW the_AT government_NN1 ,_, that_DD1 adds_VVZ a_AT1 board_NN1 of_IO directors_NN2 to_II the_AT mix_NN1 ,_, and_CC some_DD of_IO the_AT staff_NN listed_VVD above_RL will_VM report_VVI to_II them_PPHO2 instead_II21 of_II22 elected_JJ officials_NN2 ._. <p>_NULL 
</s>
<s>
Having_VHG good_JJ relationships_NN2 with_IW those_DD2 that_CST can_VM help_VVI you_PPY accomplish_VVI your_APPGE mission_NN1 is_VBZ vital_JJ to_II your_APPGE success_NN1 ._. 
</s>
<s>
A_AT1 good_JJ relationship_NN1 is_VBZ one_PN1 where_CS the_AT people_NN involved_VVN are_VBR able_JK to_TO discuss_VVI and_CC work_VVI out_RP issues_NN2 and_CC problems_NN2 that_CST will_VM arise_VVI ._. 
</s>
<s>
When_RRQ issues_NN2 come_VV0 up_RP that_DD1 could_VM weaken_VVI or_CC destroy_VVI lesser_JJ relationships_NN2 ,_, the_AT partners_NN2 work_VV0 together_RL to_TO confront_VVI and_CC overcome_VVI the_AT problems_NN2 ,_, which_DDQ also_RR strengthens_VVZ the_AT partnership_NN1 in_II the_AT process_NN1 ._. <p>_NULL 
</s>
<s>
When_CS deciding_VVG how_RRQ to_TO invest_VVI your_APPGE limited_JJ time_NNT1 in_II relationship_NN1 building_NN1 ,_, keep_VV0 in_II mind_NN1 where_CS in_II the_AT hierarchy_NN1 of_IO authority_NN1 each_DD1 individual_JJ falls_NN2 ._. 
</s>
<s>
People_NN lower_VV0 on_II the_AT list_NN1 can_VM often_RR make_VVI your_APPGE day-to-day_JJ tasks_NN2 easier_RRR or_CC more_RGR difficult_JJ ,_, and_CC those_DD2 higher_JJR on_II the_AT list_NN1 can_VM help_VVI or_CC hinder_VVI you_PPY in_II reaching_VVG your_APPGE bigger_JJR goals_NN2 ._. <p>_NULL 
</s>
<s>
For_REX21 example_REX22 ,_, the_AT government_NN1 only_RR has_VHZ resources_NN2 that_CST it_PPH1 gets_VVZ from_II its_APPGE citizens_NN2 and_CC is_VBZ dependent_JJ on_II taxpayers_NN2 ,_, especially_RR property_NN1 owners_NN2 ,_, for_IF its_APPGE revenue_NN1 ._. 
</s>
<s>
Additionally_RR ,_, the_AT people_NN that_CST run_VV0 the_AT government_NN1 depend_VV0 upon_II the_AT voters_NN2 to_TO elect_VVI them_PPHO2 and_CC then_RT decide_VVI if_CSW they_PPHS2 get_VV0 to_TO keep_VVI their_APPGE jobs_NN2 ._. 
</s>
<s>
For_IF that_DD1 reason_NN1 ,_, leveraging_VVG the_AT power_NN1 of_IO a_AT1 general_JJ constituency_NN1 can_VM often_RR get_VVI elected_JJ officials_NN2 to_TO be_VBI responsive_JJ to_II your_APPGE message_NN1 ._. <p>_NULL 
</s>
<s>
My_APPGE path_NN1 toward_II forming_VVG FCNMHP_NP1 began_VVD with_IW a_AT1 relationship_NN1 with_IW the_AT Mayor_NN1 's_GE Chief_NN1 of_IO Staff_NN through_II serving_VVG on_II a_AT1 task_NN1 force_NN1 on_II animal_NN1 control_NN1 with_IW that_DD1 individual_NN1 and_CC others_NN2 while_CS working_VVG with_IW that_DD1 task_NN1 force_NN1 ._. 
</s>
<s>
This_DD1 undoubtedly_RR eased_VVD my_APPGE ability_NN1 to_TO begin_VVI a_AT1 relationship_NN1 with_IW the_AT animal_NN1 control_NN1 department_NN1 chief_NN1 ._. 
</s>
<s>
If_CS you_PPY are_VBR working_VVG in_II animal_NN1 welfare_NN1 ,_, a_AT1 good_JJ relationship_NN1 with_IW the_AT local_JJ animal_NN1 control_NN1 is_VBZ going_VVGK to_TO be_VBI important_JJ to_II your_APPGE success_NN1 ._. 
</s>
<s>
How_RRQ do_VD0 you_PPY make_VVI this_DD1 happen_VV0 ?_? <p>_NULL 
</s>
<s>
Think_VV0 about_II the_AT way_NN1 you_PPY act_VV0 ,_, look_VV0 ,_, smell_VV0 ,_, talk_VV0 ,_, dress_VV0 ;_; all_DB of_IO these_DD2 things_NN2 are_VBR important_JJ ._. 
</s>
<s>
If_CS you_PPY are_VBR not_XX the_AT type_NN1 of_IO person_NN1 that_CST other_JJ people_NN want_VV0 to_TO get_VVI to_TO know_VVI and_CC be_VBI around_RP ,_, then_RT your_APPGE task_NN1 is_VBZ going_VVGK to_TO be_VBI very_RG difficult_JJ ._. 
</s>
<s>
This_DD1 is_VBZ not_XX to_TO say_VVI that_CST you_PPY have_VH0 to_TO be_VBI the_AT Prom_NN1 Queen_NN1 or_CC Football_NN1 Star_NN1 ,_, but_CCB you_PPY do_VD0 have_VHI to_TO be_VBI interesting_JJ and_CC interested_JJ ._. 
</s>
<s>
If_CS that_DD1 's_VBZ not_XX one_MC1 of_IO your_APPGE skills_NN2 ,_, perhaps_RR someone_PN1 else_RR in_II your_APPGE organization_NN1 should_VM be_VBI in_II31 charge_II32 of_II33 relationship_NN1 building_NN1 ._. <p>_NULL 
</s>
<s>
Do_VD0 you_PPY already_RR know_VVI the_AT animal_NN1 control_NN1 director_NN1 ?_? 
</s>
<s>
How_RRQ is_VBZ your_APPGE relationship_NN1 with_IW him_PPHO1 or_CC her_PPHO1 ?_? 
</s>
<s>
Even_CS21 if_CS22 you_PPY have_VH0 had_VHN a_AT1 negative_JJ relationship_NN1 in_II the_AT past_NN1 ,_, you_PPY still_RR may_VM be_VBI able_JK to_TO salvage_VVI it_PPH1 ,_, remember_VV0 Nixon_NP1 went_VVD to_II China_NP1 and_CC John_NP1 McCain_NP1 visited_VVD Viet_NP1 Nam_NP1 years_NNT2 after_II the_AT war_NN1 ._. 
</s>
<s>
Making_VVG amends_NN2 with_IW an_AT1 animal_NN1 control_NN1 director_NN1 may_VM not_XX be_VBI historic_JJ ,_, but_CCB it_PPH1 could_VM be_VBI a_AT1 big_JJ step_NN1 toward_II reaching_VVG your_APPGE goals_NN2 ._. <p>_NULL 
</s>
<s>
Donuts_NN2 ,_, Lunches_NN2 and_CC Listening_JJ Email_NN1 or_CC call_VV0 the_AT animal_NN1 control_NN1 director_NN1 and_CC ask_VV0 if_CS you_PPY can_VM come_VVI by_RP for_IF a_AT1 short_JJ talk_NN1 ._. 
</s>
<s>
He_PPHS1 wo_VM n't_XX answer_VVI your_APPGE call_NN1 or_CC email_NN1 ?_? 
</s>
<s>
Stop_VV0 by_RP with_IW a_AT1 couple_NN1 dozen_NNO donuts_NN2 and_CC see_VV0 if_CS you_PPY can_VM catch_VVI him_PPHO1 in_II his_APPGE office_NN1 ._. 
</s>
<s>
If_CS you_PPY get_VV0 to_TO talk_VVI to_II him_PPHO1 ,_, great_JJ ;_; if_CS not_XX ,_, leave_VV0 your_APPGE business_NN1 card_NN1 with_IW your_APPGE cell_NN1 phone_NN1 number_NN1 asking_VVG him_PPHO1 to_TO call_VVI you_PPY ._. 
</s>
<s>
Leave_VV0 the_AT donuts_NN2 and_CC spend_VV0 some_DD time_NNT1 talking_VVG to_II whoever_PNQV you_PPY can_VM ,_, taking_VVG care_NN1 not_XX to_TO get_VVI in_II the_AT way_NN1 of_IO their_APPGE work_NN1 ._. 
</s>
<s>
Be_VB0 sure_JJ you_PPY learn_VV0 something_PN1 and_CC be_VBI positive_JJ and_CC friendly_JJ ;_; especially_RR ,_, learn_VV0 names_NN2 and_CC direct_JJ contact_NN1 info_NN1 for_IF anyone_PN1 who_PNQS seems_VVZ friendly_JJ ._. 
</s>
<s>
The_AT start_NN1 of_IO a_AT1 positive_JJ relationship_NN1 !_! <p>_NULL 
</s>
<s>
Officially_RR the_AT purpose_NN1 of_IO your_APPGE call_NN1 or_CC visit_NN1 is_VBZ to_TO find_VVI out_RP what_DDQ areas_NN2 the_AT shelter_NN1 needs_VVZ help_NN1 in_II the_AT most_RRT ,_, and_CC to_TO request_VVI animal_NN1 intake_NN1 and_CC euthanasia_NN1 statistics_NN to_TO help_VVI you_PPY understand_VVI the_AT size_NN1 of_IO the_AT shelter_NN1 overpopulation_NN1 problem_NN1 ._. 
</s>
<s>
But_CCB your_APPGE real_JJ goal_NN1 for_IF the_AT visit_NN1 is_VBZ to_TO simply_RR begin_VVI a_AT1 new_JJ positive_JJ relationship_NN1 ._. 
</s>
<s>
If_CS the_AT people_NN you_PPY talk_VV0 to_II are_VBR able_JK to_TO give_VVI you_PPY some_DD statistics_NN right_RR then_RT ,_, that_DD1 's_VBZ great_JJ ._. 
</s>
<s>
If_CS they_PPHS2 need_VV0 some_DD time_NNT1 to_TO get_VVI them_PPHO2 together_RL ,_, that_DD1 gives_VVZ you_PPY another_DD1 reason_NN1 to_TO come_VVI by_II again_RT and_CC build_VVI your_APPGE relationship_NN1 further_RRR ._. <p>_NULL 
</s>
<s>
If_CS you_PPY are_VBR able_JK to_TO meet_VVI with_IW the_AT director_NN1 ,_, be_VBI sure_JJ it_PPH1 is_VBZ a_AT1 discussion_NN1 where_CS you_PPY do_VD0 more_DAR listening_NN1 than_CSN talking_VVG ._. 
</s>
<s>
Your_APPGE primary_JJ goal_NN1 for_IF this_DD1 visit_NN1 is_VBZ to_TO begin_VVI a_AT1 positive_JJ relationship_NN1 ,_, and_CC your_APPGE secondary_JJ goal_NN1 is_VBZ to_TO gain_VVI knowledge_NN1 ;_; both_DB2 of_IO these_DD2 will_VM be_VBI accomplished_VVN better_RRR if_CS you_PPY do_VD0 more_DAR listening_NN1 than_CSN talking_VVG ._. 
</s>
<s>
There_EX is_VBZ a_AT1 saying_NN1 that_CST God_NP1 gave_VVD you_PPY two_MC ears_NN2 and_CC one_MC1 mouth_NN1 for_IF a_AT1 reason_NN1 -_- that_DD1 is_VBZ probably_RR a_AT1 good_JJ ratio_NN1 ;_; plan_VV0 on_II talking_VVG half_RR as_RG much_DA1 as_CSA you_PPY listen_VV0 ._. <p>_NULL 
</s>
<s>
Once_CS you_PPY have_VH0 gathered_VVN some_DD information_NN1 ,_, take_VV0 the_AT time_NNT1 to_TO study_VVI that_DD1 information_NN1 and_CC to_TO plan_VVI and_CC undertake_VVI some_DD course_NN1 of_IO action_NN1 ._. 
</s>
<s>
If_CS you_PPY are_VBR devising_VVG a_AT1 way_NN1 to_TO help_VVI community_NN1 cats_NN2 ,_, use_VV0 any_DD ideas_NN2 or_CC thoughts_NN2 shared_VVN by_II the_AT director_NN1 during_II your_APPGE meeting_NN1 in_II that_DD1 plan_NN1 ._. <p>_NULL 
</s>
<s>
With_IW your_APPGE "_" draft_NN1 "_" plan_NN1 firmly_RR in_II place_NN1 ,_, you_PPY are_VBR now_RT ready_JJ for_IF another_DD1 visit_NN1 with_IW the_AT director_NN1 ._. 
</s>
<s>
Hopefully_RR this_DD1 time_NNT1 you_PPY may_VM be_VBI able_JK to_TO suggest_VVI a_AT1 lunch_NN1 meeting_NN1 ._. 
</s>
<s>
Lunch_NN1 meetings_NN2 are_VBR great_JJ because_CS everybody_PN1 gets_VVZ a_AT1 chance_NN1 to_TO talk_VVI and_CC everyone_PN1 has_VHZ to_TO take_VVI time_NNT1 to_TO listen_VVI while_CS they_PPHS2 are_VBR chewing_VVG their_APPGE food_NN1 ._. 
</s>
<s>
Lunch_NN1 meetings_NN2 help_VV0 to_TO balance_VVI the_AT conversation_NN1 ._. 
</s>
<s>
If_CS you_PPY do_VD0 get_VVI a_AT1 chance_NN1 to_TO go_VVI to_II lunch_NN1 ,_, you_PPY will_VM want_VVI to_TO discreetly_RR pick_VVI up_RP the_AT check_NN1 ._. <p>_NULL 
</s>
<s>
Getting_VVG With_IW the_AT Programs_NN2 <p>_NULL 
</s>
<s>
Ten_MC years_NNT2 ago_RA ,_, nearly_RR 15,000_MC cats_NN2 died_VVD in_II Jacksonville_NP1 shelters_VVZ ,_, an_AT1 average_NN1 of_IO 1,237_MC each_DD1 month_NNT1 ._. <p>_NULL 
</s>
<s>
Today_RT ,_, while_CS we_PPIS2 still_RR have_VH0 much_RR work_VV0 to_TO do_VDI ,_, that_DD1 number_NN1 has_VHZ dropped_VVN to_II 184_MC per_II month_NNT1 ._. 
</s>
<s>
In_II the_AT first_MD five_MC months_NNT2 of_IO this_DD1 year_NNT1 ,_, our_APPGE save_NN1 rate_NN1 for_IF felines_NN2 was_VBDZ 77%_NNU ._. <p>_NULL 
</s>
<s>
That_DD1 progress_NN1 has_VHZ been_VBN a_AT1 trip_NN1 of_IO many_DA2 thousands_NNO2 of_IO small_JJ steps_NN2 ,_, with_IW just_RR a_AT1 few_DA2 giant_JJ leaps_NN2 ._. 
</s>
<s>
Our_APPGE successful_JJ programs_NN2 fall_VV0 into_II two_MC categories_NN2 :_: proactive_JJ programs_NN2 ,_, and_CC reactive_JJ ones_NN2 ._. 
</s>
<s>
Finding_VVG the_AT solution_NN1 to_TO shelter_VVI overpopulation_NN1 requires_VVZ an_AT1 ever_RR changing_JJ blend_NN1 of_IO each_DD1 of_IO these_DD2 ._. 
</s>
<s>
And_CC at_II every_AT1 step_NN1 of_IO the_AT way_NN1 ,_, we_PPIS2 have_VH0 had_VHN to_TO find_VVI new_JJ and_CC creative_JJ ways_NN2 to_TO work_VVI with_IW government_NN1 officials_NN2 to_TO implement_VVI and_CC maintain_VVI those_DD2 programs_NN2 ._. <p>_NULL 
</s>
<s>
Proactive_JJ programs_NN2 are_VBR those_DD2 that_CST focus_VV0 on_II decreasing_VVG the_AT number_NN1 of_IO animals_NN2 entering_VVG the_AT shelter_NN1 ,_, and_CC take_VV0 many_DA2 different_JJ forms_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, we_PPIS2 focused_VVD on_II neutering_NN1 targeted_VVD animal_NN1 populations_NN2 :_: those_DD2 most_RRT in_II danger_NN1 of_IO entering_VVG the_AT shelter_NN1 such_II21 as_II22 cats_NN2 of_IO low_JJ income_NN1 pet_NN1 owners_NN2 ,_, cats_NN2 from_II geographically_RR high_JJ intake_NN1 areas_NN2 ,_, and_CC feral_JJ cats_NN2 ._. 
</s>
<s>
We_PPIS2 also_RR provided_VVD low-cost_JJ neutering_NN1 to_II all_DB ._. <p>_NULL 
</s>
<s>
Reactive_JJ programs_NN2 are_VBR those_DD2 that_CST work_VV0 to_TO save_VVI the_AT animals_NN2 once_CS they_PPHS2 have_VH0 reached_VVN the_AT shelters_NN2 ,_, and_CC include_VV0 adoption_NN1 programs_NN2 ,_, foster_JJ homes_NN2 ,_, working_VVG with_IW placement_NN1 partners_NN2 ,_, and_CC programs_NN2 like_II Feral_JJ Freedom_NN1 ,_, which_DDQ may_VM be_VBI the_AT single_JJ most_RGT effective_JJ program_NN1 for_IF saving_VVG the_AT lives_NN2 of_IO community_NN1 cats_NN2 entering_VVG our_APPGE shelters_NN2 ,_, who_PNQS would_VM typically_RR die_VVI without_IW this_DD1 type_NN1 of_IO intervention_NN1 ._. <p>_NULL 
</s>
<s>
Proactive_JJ Programs_NN2 Most_DAT of_IO our_APPGE resources_NN2 are_VBR focused_VVN on_II proactive_JJ programs_NN2 that_CST work_VV0 to_TO keep_VVI pets_NN2 from_II ever_RR entering_VVG shelters_NN2 ._. 
</s>
<s>
The_AT most_RGT important_JJ benefit_NN1 of_IO our_APPGE good_JJ relationship_NN1 with_IW the_AT local_JJ government_NN1 has_VHZ been_VBN the_AT ability_NN1 to_TO find_VVI funding_NN1 for_IF our_APPGE targeted_JJ spay/neuter_NN1 programs_NN2 ._. 
</s>
<s>
These_DD2 programs_NN2 are_VBR an_AT1 obvious_JJ good_JJ investment_NN1 for_IF any_DD shelter_NN1 that_CST is_VBZ faced_VVN with_IW ever_RR increasing_JJ numbers_NN2 of_IO animals_NN2 being_VBG brought_VVN to_II them_PPHO2 ._. 
</s>
<s>
Our_APPGE SpayJax_NN1 program_NN1 ,_, which_DDQ is_VBZ our_APPGE income-targeted_JJ program_NN1 ,_, has_VHZ been_VBN funded_VVN by_II the_AT city_NN1 for_IF 10_MC years_NNT2 now_RT ,_, at_II a_AT1 total_JJ investment_NN1 of_IO over_RG $2,000,000_NNU ._. 
</s>
<s>
Income-targeted_JJ programs_NN2 are_VBR the_AT most_RGT effective_JJ at_II decreasing_JJ shelter_NN1 admissions_NN2 and_CC should_VM be_VBI the_AT mainstay_NN1 spay/neuter_NN1 program_NN1 of_IO any_DD animal_NN1 welfare_NN1 program_NN1 that_CST is_VBZ serious_JJ about_II decreasing_JJ shelter_NN1 deaths_NN2 ._. 
</s>
<s>
1_MC1 <p>_NULL 
</s>
<s>
It_PPH1 became_VVD obvious_JJ with_IW ever-tightening_JJ government_NN1 budgets_VVZ that_CST a_AT1 long-term_JJ dedicated_JJ funding_NN1 source_NN1 for_IF targeted_JJ spay/neuter_NN1 programs_NN2 was_VBDZ vital_JJ ._. 
</s>
<s>
Our_APPGE good_JJ relationships_NN2 with_IW every_AT1 level_NN1 of_IO the_AT government_NN1 was_VBDZ never_RR more_RGR important_JJ than_CSN when_CS we_PPIS2 undertook_VVD the_AT job_NN1 of_IO changing_VVG the_AT ordinance_NN1 to_TO increase_VVI pet_NN1 license_NN1 fees_NN2 by_II $10_NNU and_CC require_VV0 that_CST the_AT additional_JJ revenue_NN1 be_VBI dedicated_VVN to_II funding_NN1 spay/neuter_NN1 programs_NN2 ._. 
</s>
<s>
It_PPH1 is_VBZ possible_JJ to_TO operate_VVI proactive_JJ programs_NN2 without_IW having_VHG a_AT1 good_JJ relationship_NN1 with_IW local_JJ municipalities_NN2 ,_, but_CCB having_VHG good_JJ relationships_NN2 can_VM often_RR help_VVI find_VVI ongoing_JJ funding_NN1 for_IF these_DD2 programs_NN2 and_CC is_VBZ important_JJ in_II attaining_VVG access_NN1 to_II the_AT shelter_NN1 data_NN needed_VVD to_TO ensure_VVI the_AT effectiveness_NN1 of_IO these_DD2 programs_NN2 ._. <p>_NULL 
</s>
<s>
Another_DD1 important_JJ funding_NN1 benefit_VV0 that_CST can_VM come_VVI with_IW good_JJ relations_NN2 is_VBZ the_AT ability_NN1 of_IO the_AT local_JJ government_NN1 to_TO receive_VVI grants_NN2 that_CST our_APPGE organization_NN1 is_VBZ not_XX eligible_JJ for_IF ._. 
</s>
<s>
We_PPIS2 have_VH0 worked_VVN with_IW three_MC of_IO the_AT local_JJ governments_NN2 to_TO receive_VVI large_JJ grants_NN2 for_IF targeted_JJ spay/neuter_NN1 programs_NN2 in_II their_APPGE communities_NN2 ,_, with_IW our_APPGE group_NN1 ,_, FCNMHP_NP1 ,_, being_VBG paid_VVN to_TO perform_VVI the_AT surgeries_NN2 ._. 
</s>
<s>
These_DD2 grants_NN2 are_VBR given_VVN to_II the_AT local_JJ government_NN1 entity_NN1 which_DDQ then_RT contracts_VVZ with_IW our_APPGE organization_NN1 to_TO perform_VVI the_AT services_NN2 ._. 
</s>
<s>
The_AT process_NN1 has_VHZ worked_VVN well_RR ,_, but_CCB comes_VVZ with_IW many_DA2 issues_NN2 that_CST must_VM be_VBI worked_VVN out_RP ._. 
</s>
<s>
Obviously_RR having_VHG good_JJ relationships_NN2 is_VBZ vital_JJ to_II this_DD1 type_NN1 of_IO partnership_NN1 ._. <p>_NULL 
</s>
<s>
Reactive_JJ Programs_NN2 Most_DAT of_IO our_APPGE resources_NN2 are_VBR focused_VVN on_II proactive_JJ programs_NN2 as_CSA being_VBG the_AT better_JJR long-term_JJ investment_NN1 ._. 
</s>
<s>
However_RR ,_, at_II some_DD point_NN1 in_II any_DD community_NN1 's_GE evolution_NN1 toward_II becoming_VVG no-kill_JJ ,_, resources_NN2 will_VM have_VHI to_TO be_VBI targeted_VVN at_II reactive_JJ programs_NN2 that_CST save_VV0 the_AT animals_NN2 that_CST are_VBR already_RR in_II the_AT shelters_NN2 ._. 
</s>
<s>
Adoption_NN1 programs_NN2 are_VBR the_AT obvious_JJ and_CC most_RGT widely_RR used_JJ reactive_JJ program_NN1 in_II animal_NN1 welfare_NN1 ._. 
</s>
<s>
All_DB the_AT cats_NN2 from_II our_APPGE adoption_NN1 programs_NN2 come_VV0 from_II the_AT city_NN1 shelter_NN1 ,_, plus_CC we_PPIS2 manage_VV0 large_JJ adoption_NN1 events_NN2 that_CST bring_VV0 pets_NN2 from_II many_DA2 shareholders_NN2 together_RL ._. 
</s>
<s>
Programs_NN2 like_II these_DD2 require_VV0 close_JJ cooperation_NN1 and_CC a_AT1 level_NN1 of_IO mutual_JJ respect_NN1 that_CST only_RR comes_VVZ from_II good_JJ long-term_JJ relationships_NN2 ._. <p>_NULL 
</s>
<s>
Our_APPGE most_RGT effective_JJ reactive_JJ program_NN1 came_VVD from_II an_AT1 opportunity_NN1 that_CST was_VBDZ possible_JJ due_II21 to_II22 our_APPGE relationship_NN1 with_IW the_AT Jacksonville_NP1 Mayor_NN1 's_GE office_NN1 and_CC the_AT department_NN1 director_NN1 ._. <p>_NULL 
</s>
<s>
A_AT1 string_NN1 of_IO events_NN2 occurred_VVD that_CST had_VHD left_VVN the_AT department_NN1 director_NN1 ,_, Ebenezer_NP1 Gujjarlapudi_NP1 ,_, in_II direct_JJ control_NN1 of_IO Animal_NN1 Care_NN1 and_CC Protective_JJ Services_NN2 ._. 
</s>
<s>
He_PPHS1 was_VBDZ determined_VVN to_TO fix_VVI some_DD issues_NN2 in_II the_AT department_NN1 before_II hiring_VVG a_AT1 new_JJ chief_NN1 to_TO take_VVI the_AT reins_NN2 ._. 
</s>
<s>
We_PPIS2 had_VHD a_AT1 good_JJ relationship_NN1 with_IW the_AT city_NN1 prior_II21 to_II22 the_AT chief_JJ leaving_NN1 ,_, and_CC all_DB involved_VVD were_VBDR determined_VVN to_TO keep_VVI good_JJ relationships_NN2 going_VVG through_II the_AT transition_NN1 ._. 
</s>
<s>
We_PPIS2 had_VHD made_VVN a_AT1 request_NN1 that_CST all_DB ear-tipped_JJ feral_JJ cats_NN2 were_VBDR returned_VVN to_II us_PPIO2 so_CS they_PPHS2 could_VM be_VBI returned_VVN to_II the_AT colony_NN1 where_CS they_PPHS2 were_VBDR living_VVG ._. 
</s>
<s>
Mr._NNB Gujjarlapudi_NP1 responded_VVD that_CST he_PPHS1 would_VM have_VHI to_TO study_VVI the_AT issue_NN1 ,_, as_CSA he_PPHS1 was_VBDZ not_XX deeply_RR knowledgeable_JJ about_II feral_JJ cats_NN2 and_CC he_PPHS1 would_VM like_VVI to_TO make_VVI an_AT1 informed_JJ decision_NN1 ._. 
</s>
<s>
We_PPIS2 met_VVD over_II lunch_NN1 to_TO discuss_VVI what_DDQ he_PPHS1 had_VHD decided_VVN was_VBDZ to_TO be_VBI the_AT city_NN1 's_GE new_JJ feral_JJ cat_NN1 policy_NN1 ,_, which_DDQ was_VBDZ :_: <p>_NULL 
</s>
<s>
"_" Feral_NP1 and_CC community_NN1 cats_NN2 would_VM no_RR21 longer_RR22 be_VBI killed_VVN in_II the_AT city_NN1 shelter_NN1 ._. 
</s>
<s>
Instead_RR ,_, all_DB feral_JJ cats_NN2 coming_VVG into_II the_AT shelter_NN1 would_VM be_VBI turned_VVN over_RP to_II FCNMHP_NP1 or_CC other_JJ animal_NN1 welfare_NN1 organizations_NN2 ._. 
</s>
<s>
These_DD2 organizations_NN2 would_VM sterilize_VVI ,_, vaccinate_VV0 ,_, microchip_NN1 ,_, ear_NN1 tip_NN1 and_CC return_VV0 the_AT cats_NN2 to_II their_APPGE territories_NN2 ._. "_" <p>_NULL 
</s>
<s>
Although_CS this_DD1 was_VBDZ more_RRR than_CSN we_PPIS2 had_VHD asked_VVN for_IF or_CC budgeted_VVD for_IF ,_, it_PPH1 was_VBDZ clearly_RR an_AT1 opportunity_NN1 that_CST was_VBDZ too_RG good_JJ to_TO pass_VVI up_RP ._. 
</s>
<s>
This_DD1 new_JJ policy_NN1 resulted_VVN in_II the_AT Feral_JJ Freedom_NN1 program_NN1 that_CST has_VHZ saved_VVN over_RG 15,000_MC community_NN1 cats_NN2 from_II death_NN1 in_II the_AT shelter_NN1 by_II diverting_VVG them_PPHO2 to_II our_APPGE facility_NN1 ,_, where_CS they_PPHS2 are_VBR sterilized_VVN ,_, vaccinated_VVD ,_, ear-tipped_NN1 ,_, and_CC returned_VVN to_II their_APPGE territory_NN1 ._. 
</s>
<s>
A_AT1 complete_JJ guide_NN1 to_II the_AT Feral_JJ Freedom_NN1 program_NN1 can_VM be_VBI found_VVN here_RL ._. <p>_NULL 
</s>
<s>
It_PPH1 was_VBDZ during_II this_DD1 time_NNT1 period_NN1 that_CST we_PPIS2 started_VVD to_TO use_VVI the_AT term_NN1 "_" community_NN1 cat_NN1 "_" for_IF the_AT cats_NN2 coming_VVG through_II this_DD1 program_NN1 ,_, as_CSA we_PPIS2 quickly_RR realized_VVN that_CST most_DAT of_IO the_AT cats_NN2 could_VM not_XX actually_RR be_VBI called_VVN "_" feral_NN1 ._. "_" 
</s>
<s>
They_PPHS2 were_VBDR living_VVG outside_RL ,_, either_RR alone_RR ,_, in_II pairs_NN2 ,_, or_CC in_II small_JJ groups_NN2 ,_, rather_CS21 than_CS22 in_II large_JJ colonies_NN2 ._. 
</s>
<s>
Additionally_RR ,_, these_DD2 cats_NN2 were_VBDR being_VBG loosely_RR cared_VVN for_IF by_II one_MC1 or_CC more_DAR people_NN in_II the_AT community_NN1 ._. <p>_NULL 
</s>
<s>
Our_APPGE good_JJ relationship_NN1 with_IW the_AT city_NN1 allows_VVZ us_PPIO2 to_TO operate_VVI programs_NN2 such_II21 as_II22 this_DD1 ,_, but_CCB we_PPIS2 also_RR carefully_RR monitor_VV0 the_AT results_NN2 and_CC impacts_NN2 on_II shelter_NN1 admissions_NN2 and_CC deaths_NN2 ._. 
</s>
<s>
The_AT Feral_JJ Freedom_NN1 program_NN1 resulted_VVN in_II a_AT1 huge_JJ decrease_NN1 in_II feline_JJ shelter_NN1 deaths_NN2 ._. 
</s>
<s>
Working_VVG with_IW animal_NN1 services_NN2 ,_, we_PPIS2 continually_RR analyze_VV0 the_AT shelter_NN1 statistics_NN to_TO assist_VVI in_II making_VVG changes_NN2 to_II existing_JJ programs_NN2 or_CC designing_VVG and_CC implementing_VVG new_JJ programs_NN2 ._. <p>_NULL 
</s>
<s>
Once_CS 4000+_FO fewer_DAR cats_NN2 were_VBDR dying_VVG in_II the_AT shelter_NN1 ,_, it_PPH1 became_VVD obvious_JJ that_CST the_AT next_MD largest_JJT group_NN1 of_IO feline_JJ shelter_NN1 deaths_NN2 were_VBDR neo-natal_JJ kittens_NN2 that_CST could_VM be_VBI adopted_VVN but_CCB just_RR needed_VVN to_TO get_VVI a_RR21 little_RR22 older_JJR and_CC stay_VV0 healthy_JJ until_CS they_PPHS2 were_VBDR old_JJ enough_RR for_IF adoption_NN1 ._. 
</s>
<s>
This_DD1 realization_NN1 brought_VVD about_RP a_AT1 cooperative_JJ effort_NN1 by_II the_AT three_MC largest_JJT animal_NN1 welfare_NN1 shareholders_NN2 to_TO increase_VVI foster_JJ home_NN1 capacity_NN1 and_CC to_TO open_VVI a_AT1 neo-natal_JJ kitten_NN1 nursery_NN1 where_CS underage_JJ kittens_NN2 admitted_VVN to_II the_AT shelter_NN1 could_VM be_VBI transferred_VVN to_TO keep_VVI them_PPHO2 healthy_JJ until_CS they_PPHS2 were_VBDR old_JJ enough_RR for_IF adoption_NN1 ._. <p>_NULL 
</s>
<s>
This_DD1 initiative_NN1 was_VBDZ too_RG large_JJ for_IF any_DD one_MC1 of_IO our_APPGE organizations_NN2 ,_, so_CS it_PPH1 has_VHZ been_VBN taken_VVN on_RP as_II a_AT1 cooperative_JJ effort_NN1 between_II Jacksonville_NP1 Animal_NN1 Care_NN1 and_CC Protective_JJ Services_NN2 ,_, Jacksonville_NP1 Humane_JJ Society_NN1 ,_, and_CC FCNMHP_NP1 ._. 
</s>
<s>
Without_IW continued_JJ good_JJ relationships_NN2 between_II these_DD2 three_MC organizations_NN2 ,_, a_AT1 project_NN1 like_II this_DD1 would_VM not_XX be_VBI possible_JJ ._. <p>_NULL 
</s>
<s>
Good_JJ positive_JJ relationships_NN2 lead_VV0 to_II opportunities_NN2 ,_, which_DDQ lead_VV0 to_II lives_NN2 saved_VVD ._. <p>_NULL 
</s>
<s>
Good_JJ relationships_NN2 help_VV0 to_TO open_VVI doors_NN2 to_II all_DB kinds_NN2 of_IO access_NN1 and_CC influence_VV0 you_PPY might_VM not_XX have_VHI otherwise_RR ._. 
</s>
<s>
If_CS you_PPY invest_VV0 your_APPGE time_NNT1 in_II building_VVG a_AT1 relationship_NN1 with_IW the_AT animal_NN1 control_NN1 director_NN1 and_CC having_VHG good_JJ relationships_NN2 with_IW those_DD2 above_RL and_CC below_RL you_PPY on_II the_AT organizational_JJ chart_NN1 ,_, then_RT you_PPY are_VBR setting_VVG yourself_PPX1 up_RP for_IF success_NN1 ,_, especially_RR in_II the_AT case_NN1 that_CST any_DD of_IO those_DD2 players_NN2 are_VBR no_RR21 longer_RR22 in_II the_AT game_NN1 ._. 
</s>
<s>
Good_JJ relations_NN2 with_IW those_DD2 above_II the_AT director_NN1 may_VM allow_VVI you_PPY input_VV0 on_II selecting_VVG a_AT1 replacement_NN1 director_NN1 if_CS that_DD1 arises_VVZ ._. 
</s>
<s>
It_PPH1 also_RR helps_VVZ if_CS the_AT new_JJ director_NN1 is_VBZ instructed_VVN when_CS hired_VVN that_DD1 part_NN1 of_IO the_AT job_NN1 is_VBZ having_VHG good_JJ relationships_NN2 with_IW you_PPY ._. 
</s>
<s>
Time_NNT1 is_VBZ one_MC1 of_IO our_APPGE most_RGT valuable_JJ resources_NN2 ,_, but_CCB time_NNT1 spent_VVN building_VVG good_JJ relationships_NN2 with_IW those_DD2 who_PNQS can_VM help_VVI our_APPGE cause_NN1 is_VBZ an_AT1 investment_NN1 that_CST will_VM pay_VVI dividends_NN2 in_II lives_NN2 saved_VVD now_RT and_CC in_II the_AT future_NN1 ._. <p>_NULL 
</s>
<s>
About_II the_AT author_NN1 :_: Rick_NP1 DuCharme_NP1 came_VVD to_II the_AT animal_NN1 welfare_NN1 world_NN1 with_IW a_AT1 background_NN1 in_II sales_NN ,_, marketing_NN1 and_CC management_NN1 working_VVG in_II the_AT heavy_JJ equipment_NN1 industry_NN1 ._. 
</s>
<s>
He_PPHS1 started_VVD in_II animal_NN1 welfare_NN1 by_II volunteering_VVG at_II various_JJ shelters_NN2 and_CC rescues_NN2 and_CC spent_VVD years_NNT2 observing_VVG and_CC researching_VVG the_AT issues_NN2 ._. 
</s>
<s>
In_II 2001_MC Rick_NP1 was_VBDZ appointed_VVN by_II Mayor_NNB Delaney_NP1 of_IO Jacksonville_NP1 to_TO serve_VVI on_II the_AT "_" Mayor_NN1 's_GE Task_NN1 Force_NN1 for_IF Animal_NN1 Control_NN1 "_" and_CC was_VBDZ a_AT1 strong_JJ advocate_NN1 for_IF an_AT1 effective_JJ spay/neuter_NN1 program_NN1 ._. <p>_NULL 
</s>
<s>
In_II 2002_MC ,_, Rick_NP1 founded_VVD First_MD Coast_NN1 No_AT More_RGR Homeless_JJ Pets_NN2 ,_, an_AT1 organization_NN1 dedicated_VVN to_II ending_VVG the_AT killing_NN1 of_IO dogs_NN2 and_CC cats_NN2 in_II Jacksonville_NP1 and_CC beyond_RL ._. 
</s>
<s>
The_AT same_DA year_NNT1 ,_, the_AT SpayJax_NN1 program_NN1 was_VBDZ introduced_VVN as_CSA one_MC1 of_IO the_AT first_MD government_NN1 funded_VVN ,_, targeted_VVD spay/neuter_NN1 programs_NN2 in_II the_AT southeast_ND1 ._. 
</s>
<s>
The_AT SpayJax_NN1 program_NN1 continues_VVZ today_RT and_CC is_VBZ widely_RR given_VVN credit_NN1 for_IF reversing_VVG the_AT trend_NN1 of_IO increasing_JJ volumes_NN2 of_IO dogs_NN2 and_CC cats_NN2 entering_VVG and_CC dying_VVG in_II Jacksonville_NP1 's_GE shelters_NN2 ._. <p>_NULL 
</s>
<s>
FCNMHP_NP1 opened_VVD their_APPGE first_MD small_JJ spay/neuter_NN1 clinic_NN1 that_CST focused_VVD on_II feral_JJ cats_NN2 and_CC then_RT domestic_JJ cats_NN2 in_II 2008_MC ._. 
</s>
<s>
A_AT1 year_NNT1 later_RRR ,_, FCNMHP_NP1 opened_VVD one_MC1 of_IO the_AT largest_JJT spay/neuter_NN1 clinics_NN2 in_II the_AT country_NN1 ._. 
</s>
<s>
This_DD1 clinic_NN1 is_VBZ currently_RR operating_VVG at_II a_AT1 capacity_NN1 of_IO 105_MC surgeries_NN2 per_II day_NNT1 with_IW room_NN1 enough_RR for_IF up_RG21 to_RG22 220_MC surgeries_NN2 per_II day_NNT1 with_IW more_DAR equipment_NN1 and_CC staff_NN ._. 
</s>
<s>
To_II date_NN1 ,_, FCNMHP_NP1 has_VHZ facilitated_VVN over_RG 115,000_MC spay_NN1 and_CC neuter_JJ surgeries_NN2 ._. <p>_NULL 
</s>
<s>
Working_VVG with_IW the_AT City_NN1 of_IO Jacksonville_NP1 the_AT Feral_JJ Freedom_NN1 program_NN1 was_VBDZ introduced_VVN in_II 2008_MC ;_; a_AT1 first_MD in_II the_AT nation_NN1 ._. 
</s>
<s>
Feral_JJ Freedom_NN1 is_VBZ a_AT1 public/private_JJ collaboration_NN1 to_TO save_VVI all_DB the_AT cats_NN2 that_CST come_VV0 into_II the_AT city_NN1 's_GE shelters_NN2 ._. 
</s>
<s>
This_DD1 program_NN1 is_VBZ saving_VVG the_AT lives_NN2 of_IO nearly_RR 5,000_MC cats_NN2 each_DD1 year_NNT1 and_CC reducing_VVG the_AT feral_JJ cat_NN1 population_NN1 ._. <p>_NULL 
</s>
<s>
Rick_NP1 mentors_NN2 non-profits_NN2 and_CC animal_NN1 control_NN1 organizations_NN2 from_II across_II the_AT country_NN1 ._. 
</s>
<s>
He_PPHS1 helps_VVZ them_PPHO2 start_VVI similar_JJ programs_NN2 in_II their_APPGE communities_NN2 ,_, saving_VVG even_RR more_DAR lives_NN2 nationwide_RL ._. 
</s>
