<s>
<0216610>_NULL <h>_NULL Clinical_JJ Scenario_NN1 <p>_NULL 
</s>
<s>
You_PPY are_VBR working_VVG as_II an_AT1 internal_JJ medicine_NN1 resident_NN1 in_II a_AT1 rheumatology_NN1 rotation_NN1 and_CC are_VBR seeing_VVG a_AT1 19_MC year-old_JJ woman_NN1 who_PNQS has_VHZ had_VHN systemic_JJ lupus_NN1 erythematosus_NN1 diagnosed_VVN on_II the_AT basis_NN1 of_IO a_AT1 characteristic_JJ skin_NN1 rash_NN1 ,_, arthritis_NN1 ,_, and_CC renal_JJ disease_NN1 ._. 
</s>
<s>
A_AT1 renal_JJ biopsy_NN1 has_VHZ shown_VVN diffuse_JJ proliferative_JJ nephritis_NN1 ._. 
</s>
<s>
A_AT1 year_NNT1 ago_RA ,_, her_APPGE creatinine_NN1 was_VBDZ 140_MC micromoles/litre_FU ,_, six_MC months_NNT2 ago_RA 180_MC ,_, and_CC in_II a_AT1 blood_NN1 sample_NN1 taken_VVN a_AT1 week_NNT1 before_CS this_DD1 clinic_NN1 visit_NN1 ,_, 220_MC ._. 
</s>
<s>
Over_II the_AT last_MD year_NNT1 she_PPHS1 has_VHZ been_VBN taking_VVG prednisone_NN1 ,_, and_CC over_II the_AT last_MD six_MC months_NNT2 ,_, cyclophosphamide_VV0 ,_, both_RR in_II appropriate_JJ doses_NN2 ._. <p>_NULL 
</s>
<s>
You_PPY are_VBR distressed_VVN by_II the_AT rising_JJ creatinine_NN1 and_CC the_AT rheumatology_NN1 fellow_NN1 with_IW whom_PNQO you_PPY discuss_VV0 the_AT problem_NN1 suggests_VVZ that_CST you_PPY contact_VV0 the_AT hematology_NN1 service_NN1 to_TO consider_VVI a_AT1 trial_NN1 of_IO plasmapheresis_NN1 ._. 
</s>
<s>
She_PPHS1 states_VVZ that_DD1 plasmapheresis_NN1 is_VBZ effective_JJ in_II reducing_VVG the_AT level_NN1 of_IO the_AT antibodies_NN2 responsible_JJ for_IF the_AT nephritis_NN1 ,_, and_CC cites_VVZ a_AT1 number_NN1 of_IO trials_NN2 that_CST have_VH0 suggested_VVN therapy_NN1 is_VBZ beneficial_JJ ._. 
</s>
<s>
When_CS you_PPY ask_VV0 her_PPHO1 if_CS any_DD of_IO the_AT studies_NN2 were_VBDR randomized_VVN clinical_JJ trials_NN2 ,_, she_PPHS1 acknowledges_VVZ that_CST she_PPHS1 is_VBZ uncertain_JJ ._. <p>_NULL 
</s>
<s>
You_PPY present_VV0 the_AT dilemma_NN1 to_II the_AT attending_VVG physician_NN1 who_PNQS responds_VVZ with_IW a_AT1 suggestion_NN1 that_CST ,_, before_CS you_PPY make_VV0 a_AT1 decision_NN1 ,_, you_PPY review_VV0 the_AT relevant_JJ literature_NN1 ._. 
</s>
<s>
She_PPHS1 recommends_VVZ that_CST you_PPY bring_VV0 the_AT patient_NN1 back_RP in_II two_MC weeks_NNT2 ,_, at_II which_DDQ time_VV0 you_PPY can_VM offer_VVI her_PPHO1 the_AT appropriate_JJ therapy_NN1 ._. 
</s>
<s>
<h>_NULL The_AT Search_NN1 <p>_NULL 
</s>
<s>
You_PPY decide_VV0 that_CST the_AT most_RGT helpful_JJ article_NN1 would_VM include_VVI patients_NN2 with_IW severe_JJ lupus_NN1 that_CST threatens_VVZ renal_JJ function_NN1 and_CC who_PNQS are_VBR ,_, already_RR receiving_VVG immunosuppressive_JJ agents_NN2 ._. 
</s>
<s>
Plasmapheresis_NN1 must_VM be_VBI compared_VVN with_IW a_AT1 control_NN1 management_NN1 strategy_NN1 ,_, and_CC patients_NN2 must_VM be_VBI randomized_VVN to_TO receive_VVI or_CC not_XX receive_VVI the_AT plasmapheresis_NN1 ._. 
</s>
<s>
Finally_RR ,_, the_AT article_NN1 must_VM report_VVI clinically_RR important_JJ outcomes_NN2 ,_, such_II21 as_II22 deterioration_NN1 in_II renal_JJ function_NN1 ._. 
</s>
<s>
You_PPY are_VBR familiar_JJ with_IW the_AT software_NN1 program_NN1 "_" Grateful_JJ Med_JJ "_" and_CC use_VV0 it_PPH1 for_IF your_APPGE search_NN1 ._. 
</s>
<s>
The_AT program_NN1 provides_VVZ a_AT1 listing_NN1 of_IO Medical_JJ subject_NN1 (_( MeSH_NN1 )_) headings_NN2 ,_, and_CC you_PPY quickly_RR find_VV0 that_DD1 "_" lupus_NN1 nephritis_NN1 "_" is_VBZ one_MC1 such_DA heading_NN1 and_CC "_" plasmapheresis_NN1 "_" another_DD1 ._. 
</s>
<s>
You_PPY add_VV0 a_AT1 methodological_JJ term_NN1 that_CST will_VM restrict_VVI your_APPGE results_NN2 to_II high_JJ quality_NN1 studies_NN2 ,_, "_" randomized_VVD controlled_JJ trial_NN1 (_( PT_FO )_) "_" (_( PT_NN1 stands_VVZ for_IF publication_NN1 type_NN1 )_) ._. 
</s>
<s>
The_AT search_NN1 ,_, which_DDQ you_PPY restrict_VV0 to_II English-language_JJ articles_NN2 ,_, yields_VVZ a_AT1 total_NN1 of_IO three_MC papers_NN2 ._. 
</s>
<s>
One_MC1 is_VBZ a_AT1 trial_NN1 of_IO prednisone_NN1 and_CC cyclophosphamide_NN1 &lsqb;_( 1_MC1 &rsqb;_) ;_; a_AT1 second_NNT1 examines_VVZ the_AT effect_NN1 of_IO plasmapheresis_NN1 on_II risk_NN1 of_IO infection_NN1 &lsqb;_( 2_MC &rsqb;_) ._. 
</s>
<s>
The_AT third_MD citation_NN1 ,_, which_DDQ describes_VVZ "_" a_AT1 controlled_JJ trial_NN1 of_IO plasmapheresis_NN1 "_" ,_, appears_VVZ most_DAT likely_JJ to_TO address_VVI the_AT issue_NN1 at_II hand_NN1 ,_, the_AT effectiveness_NN1 of_IO plasmapheresis_NN1 in_II improving_VVG clinically_RR important_JJ outcomes_NN2 ._. <p>_NULL 
</s>
<s>
The_AT relevant_JJ article_NN1 is_VBZ a_AT1 randomized_JJ trial_NN1 in_II which_DDQ 46_MC patients_NN2 received_VVD a_AT1 standard_JJ therapeutic_JJ regimen_NN1 of_IO prednisone_NN1 and_CC cyclophosphamide_NN1 ,_, and_CC 40_MC patients_NN2 received_VVD standard_JJ therapy_NN1 plus_II plasmapheresis_NN1 &lsqb;_( 3_MC &rsqb;_) ._. 
</s>
<s>
Despite_II the_AT fact_NN1 that_CST antibody_NN1 levels_NN2 decreased_VVN in_II those_DD2 undergoing_VVG plasmapheresis_NN1 ,_, there_EX was_VBDZ a_AT1 trend_NN1 toward_II a_AT1 greater_JJR proportion_NN1 of_IO the_AT plasmapheresis-treated_JJ patients_NN2 dying_VVG (_( 20%_NNU versus_II 13%_NNU )_) or_CC developing_JJ renal_JJ failure_NN1 (_( 25%_NNU versus_II 17%_NNU )_) ._. 
</s>
<s>
This_DD1 seems_VVZ to_TO settle_VVI the_AT issue_NN1 of_IO whether_CSW to_TO offer_VVI your_APPGE patient_JJ plasmapheresis_NN1 ._. 
</s>
<s>
You_PPY wonder_VV0 ,_, however_RR ,_, whether_CSW the_AT study_NN1 could_VM have_VHI led_VVN to_II an_AT1 inaccurate_JJ or_CC biased_JJ outcome_NN1 ._. 
</s>
<s>
The_AT remainder_NN1 of_IO this_DD1 paper_NN1 will_VM provide_VVI you_PPY with_IW the_AT tools_NN2 to_TO address_VVI this_DD1 question_NN1 ._. 
</s>
<s>
<h>_NULL Introduction_NN1 <p>_NULL 
</s>
<s>
In_II the_AT first_MD section_NN1 in_II this_DD1 series_NN we_PPIS2 introduced_VVD a_AT1 framework_NN1 for_IF using_VVG the_AT medical_JJ literature_NN1 to_TO solve_VVI patient_JJ problems_NN2 and_CC provide_VVI better_JJR clinical_JJ care_NN1 &lsqb;_( 4_MC &rsqb;_) ._. 
</s>
<s>
This_DD1 second_NNT1 section_NN1 begins_VVZ the_AT discussion_NN1 of_IO how_RRQ to_TO use_VVI an_AT1 article_NN1 dealing_VVG with_IW therapy_NN1 or_CC prevention_NN1 ._. 
</s>
<s>
We_PPIS2 will_VM use_VVI the_AT term_NN1 therapy_NN1 in_II a_AT1 broad_JJ sense_NN1 ._. 
</s>
<s>
As_CSA we_PPIS2 've_VH0 described_VVN elsewhere_RL &lsqb;_( 5_MC &rsqb;_) ,_, the_AT same_DA guides_NN2 can_VM be_VBI applied_VVN to_II evaluation_NN1 of_IO therapeutic_JJ interventions_NN2 (_( directed_VVN at_II reducing_VVG symptoms_NN2 and_CC curing_VVG disease_NN1 )_) and_CC preventive_JJ interventions_NN2 (_( directed_VVN at_II reducing_VVG the_AT risk_NN1 of_IO disease_NN1 ,_, or_CC disease_NN1 complications_NN2 )_) ._. 
</s>
<s>
<h>_NULL The_AT framework_NN1 <p>_NULL 
</s>
<s>
As_CSA with_IW articles_NN2 on_II other_JJ clinical_JJ questions_NN2 ,_, one_MC1 can_VM usefully_RR pose_VVI three_MC questions_NN2 about_II an_AT1 article_NN1 on_II therapy_NN1 ._. <p>_NULL 
</s>
<s>
Are_VBR the_AT results_NN2 of_IO the_AT study_NN1 valid_JJ ?_? <p>_NULL 
</s>
<s>
This_DD1 question_NN1 has_VHZ to_TO do_VDI with_IW the_AT validity_NN1 or_CC accuracy_NN1 of_IO the_AT results_NN2 and_CC considers_VVZ whether_CSW the_AT treatment_NN1 effect_NN1 reported_VVN in_II the_AT article_NN1 represents_VVZ the_AT true_JJ direction_NN1 and_CC magnitude_NN1 of_IO the_AT treatment_NN1 effect_NN1 ._. 
</s>
<s>
Another_DD1 way_NN1 to_TO state_VVI this_DD1 question_NN1 is_VBZ :_: do_VD0 these_DD2 results_NN2 represent_VVI an_AT1 unbiased_JJ estimate_NN1 of_IO the_AT treatment_NN1 effect_NN1 ,_, or_CC have_VH0 they_PPHS2 been_VBN influenced_VVN in_II some_DD systematic_JJ fashion_NN1 to_TO lead_VVI to_II a_AT1 false_JJ conclusion_NN1 ?_? <p>_NULL 
</s>
<s>
What_DDQ were_VBDR the_AT results_NN2 ?_? <p>_NULL 
</s>
<s>
If_CS the_AT results_NN2 are_VBR valid_JJ and_CC the_AT study_NN1 likely_RR yields_VVZ an_AT1 unbiased_JJ assessment_NN1 of_IO treatment_NN1 effect_NN1 ,_, then_RT the_AT results_NN2 are_VBR worth_II examining_VVG further_RRR ._. 
</s>
<s>
This_DD1 second_NNT1 question_NN1 considers_VVZ the_AT size_NN1 and_CC precision_NN1 of_IO the_AT treatment_NN1 's_GE effect_NN1 ._. 
</s>
<s>
The_AT best_JJT estimate_NN1 of_IO that_DD1 effect_NN1 will_VM be_VBI the_AT study_NN1 findings_NN2 themselves_PPX2 ;_; the_AT precision_NN1 of_IO the_AT estimate_NN1 will_VM be_VBI superior_JJ in_II larger_JJR studies_NN2 ._. <p>_NULL 
</s>
<s>
Will_VM the_AT results_NN2 help_VVI me_PPIO1 in_II caring_VVG for_IF my_APPGE patients_NN2 ?_? <p>_NULL 
</s>
<s>
This_DD1 question_NN1 has_VHZ two_MC parts_NN2 ._. 
</s>
<s>
First_MD ,_, are_VBR the_AT results_NN2 applicable_JJ to_II your_APPGE patient_NN1 ?_? 
</s>
<s>
You_PPY should_VM hesitate_VVI to_II institute_NN1 the_AT treatment_NN1 if_CS either_RR your_APPGE patient_NN1 is_VBZ too_RG dissimlar_JJ from_II those_DD2 in_II the_AT trial_NN1 ,_, or_CC if_CS the_AT outcome_NN1 that_CST has_VHZ been_VBN improved_VVN is_VBZ n't_XX important_JJ to_II your_APPGE patient_NN1 ._. 
</s>
<s>
Second_MD ,_, if_CS the_AT results_NN2 are_VBR applicable_JJ what_DDQ is_VBZ the_AT net_JJ impact_NN1 of_IO the_AT treatment_NN1 ?_? 
</s>
<s>
The_AT impact_NN1 depends_VVZ both_RR benefits_NN2 and_CC risks_NN2 (_( side-effects_NN2 and_CC toxicity_NN1 )_) of_IO treatment_NN1 and_CC the_AT consequences_NN2 of_IO withholding_JJ treatment_NN1 ._. 
</s>
<s>
Thus_RR ,_, even_RR an_AT1 effective_JJ therapy_NN1 might_VM be_VBI withheld_VVN when_CS a_AT1 patient_NN1 's_GE prognosis_NN1 is_VBZ already_RR good_JJ without_IW treatment_NN1 ,_, especially_RR when_CS the_AT treatment_NN1 is_VBZ accompanied_VVN by_II important_JJ side-effects_NN2 and_CC toxicity_NN1 ._. <p>_NULL 
</s>
<s>
We_PPIS2 summarize_VV0 our_APPGE approach_NN1 to_II evaluating_VVG and_CC applying_VVG the_AT results_NN2 of_IO articles_NN2 addressing_VVG therapeutic_JJ effectiveness_NN1 in_II Table_NN1 1_MC1 ._. 
</s>
<s>
Housestaff_VV0 and_CC practising_JJ physicians_NN2 alike_RR need_VV0 an_AT1 approach_NN1 that_CST is_VBZ both_RR efficient_JJ and_CC comprehensive_JJ ._. 
</s>
<s>
We_PPIS2 have_VH0 therefore_RR labelled_VVN validity_NN1 criteria_NN2 as_CSA "_" primary_JJ "_" --_NN1 those_DD2 few_DA2 that_CST can_VM quickly_RR be_VBI applied_VVN by_II readers_NN2 with_IW limited_JJ time_NNT1 --_NN1 and_CC "_" secondary_JJ "_" --_NN1 those_DD2 which_DDQ ,_, though_CS still_RR important_JJ ,_, can_VM be_VBI reserved_VVN for_IF articles_NN2 that_CST pass_VV0 the_AT initial_JJ guides_NN2 and_CC for_IF readers_NN2 who_PNQS have_VH0 both_RR the_AT need_NN1 and_CC the_AT time_NNT1 for_IF a_AT1 deeper_JJR review_NN1 ._. 
</s>
<s>
<h>_NULL III_MC ._. 
</s>
<s>
Will_VM the_AT results_NN2 help_VVI me_PPIO1 in_II caring_VVG for_IF my_APPGE patients_NN2 ?_? 
</s>
<s>
<h>_NULL Are_VBR the_AT results_NN2 of_IO this_DD1 article_NN1 valid_JJ ?_? 
</s>
<s>
<h>_NULL A._NP1 Primary_JJ Guides_NN2 <h>_NULL 1_MC1 ._. 
</s>
<s>
Was_VBDZ the_AT assignment_NN1 of_IO patients_NN2 to_II treatment_NN1 randomized_VVD ?_? <p>_NULL 
</s>
<s>
During_II the_AT 1970s_MC2 and_CC early_JJ 1980s_MC2 surgeons_NN2 increasing_VVG undertook_VVD bypass_NN1 (_( that_REX21 is_REX22 ,_, anastomosis_NN1 of_IO a_AT1 branch_NN1 of_IO the_AT external_JJ carotid_JJ artery_NN1 ,_, the_AT superficial_JJ temporal_JJ ,_, to_II a_AT1 branch_NN1 of_IO the_AT internal_JJ carotid_JJ artery_NN1 ,_, the_AT middle_JJ cerebral_JJ )_) ._. 
</s>
<s>
They_PPHS2 believed_VVD it_PPH1 prevented_VVD strokes_NN2 in_II patients_NN2 whose_DDQGE symptomatic_JJ cerebrovascular_JJ disease_NN1 was_VBDZ otherwise_RR surgically_RR inaccessible_JJ ._. 
</s>
<s>
This_DD1 conviction_NN1 was_VBDZ based_VVN on_II the_AT comparison_NN1 of_IO clinical_JJ outcomes_NN2 among_II non-randomized_JJ "_" cohorts_NN2 "_" of_IO patients_NN2 who_PNQS ,_, for_IF whatever_DDQV reason_NN1 ,_, had_VHD and_CC had_VHD not_XX undergone_VVN this_DD1 operation_NN1 ,_, for_IF the_AT former_DA appeared_VVD to_TO fare_VVI much_RR better_RRR than_CSN the_AT latter_DA ._. 
</s>
<s>
To_II the_AT surprise_NN1 of_IO many_DA2 and_CC the_AT indignation_NN1 of_IO a_AT1 few_DA2 ,_, a_AT1 large_JJ multi-center_NN1 randomized_VVD trial_NN1 ,_, in_II which_DDQ patients_NN2 were_VBDR allocated_VVN to_TO receive_VVI or_CC forego_VVI this_DD1 operation_NN1 using_VVG a_AT1 process_NN1 analogous_JJ to_II flipping_VVG a_AT1 coin_NN1 ,_, demonstrated_VVD that_CST the_AT only_JJ effect_NN1 of_IO surgery_NN1 was_VBDZ to_TO make_VVI patients_NN2 worse_RRR off_RP in_II the_AT immediate_JJ post-surgical_JJ period_NN1 ;_; long-term_JJ outcome_NN1 was_VBDZ unaffected_JJ &lsqb;_( 6_MC &rsqb;_) ._. 
</s>
<s>
Other_JJ surprises_NN2 generated_VVN by_II randomized_JJ trials_NN2 that_CST contradicted_VVD the_AT results_NN2 of_IO less_RGR rigorous_JJ trials_NN2 include_VV0 the_AT demonstration_NN1 that_CST steroids_NN2 may_VM increase_VVI (_( rather_CS21 than_CS22 reduce_VVI )_) mortality_NN1 in_II patients_NN2 with_IW sepsis_NN1 &lsqb;_( 7_MC &rsqb;_) ,_, that_DD1 steroid_JJ injections_NN2 do_VD0 not_XX ameliorate_VVI facet-joint_JJ back_NN1 pain_NN1 &lsqb;_( 8_MC &rsqb;_) ,_, and_CC that_DD1 plasmapheresis_NN1 does_VDZ not_XX benefit_VVI patients_NN2 with_IW polymyositis_NN1 &lsqb;_( 9_MC &rsqb;_) ._. 
</s>
<s>
Such_DA surprises_NN2 may_VM occur_VVI when_RRQ treatments_NN2 are_VBR assigned_VVN by_II random_JJ allocation_NN1 ,_, rather_CS21 than_CS22 by_II the_AT conscious_JJ decisions_NN2 of_IO clinicians_NN2 and_CC patients_NN2 ._. 
</s>
<s>
In_RR21 short_RR22 ,_, clinical_JJ outcomes_NN2 result_VV0 from_II many_DA2 causes_NN2 ,_, and_CC treatment_NN1 is_VBZ just_RR one_MC1 of_IO them_PPHO2 :_: underlying_JJ severity_NN1 of_IO illness_NN1 ,_, the_AT presence_NN1 of_IO comorbid_JJ conditions_NN2 ,_, and_CC a_AT1 host_NN1 of_IO other_JJ prognostic_JJ factors_NN2 (_( unknown_JJ as_II31 well_II32 as_II33 known_JJ )_) often_RR swamp_VV0 any_DD effect_NN1 of_IO therapy_NN1 ._. 
</s>
<s>
Because_CS these_DD2 other_JJ features_NN2 also_RR influence_VV0 the_AT clinician_NN1 's_GE decision_NN1 to_TO offer_VVI the_AT treatment_NN1 at_II issue_NN1 ,_, nonrandomized_VVD studies_NN2 of_IO efficacy_NN1 are_VBR inevitably_RR limited_VVN in_II their_APPGE ability_NN1 to_TO distinguish_VVI useful_JJ from_II useless_JJ or_CC even_RR harmful_JJ therapy_NN1 ._. 
</s>
<s>
As_CSA confirmation_NN1 of_IO this_DD1 fact_NN1 ,_, it_PPH1 turns_VVZ out_RP that_CST studies_NN2 in_II which_DDQ treatment_NN1 is_VBZ allocated_VVN by_II any_DD method_NN1 other_II21 than_II22 randomization_NN1 tend_VV0 to_TO show_VVI larger_JJR (_( and_CC frequently_RR "_" false-positive_JJ "_" )_) treatment_NN1 effects_NN2 than_CSN do_VD0 randomized_JJ trials_NN2 &lsqb;_( 10_MC &rsqb;_) &lsqb;_( 11_MC &rsqb;_) &lsqb;_( 12_MC &rsqb;_) &lsqb;_( 13_MC &rsqb;_) ._. 
</s>
<s>
The_AT beauty_NN1 of_IO randomization_NN1 is_VBZ that_CST it_PPH1 assures_VVZ ,_, if_CS sample_NN1 size_NN1 is_VBZ sufficiently_RR large_JJ ,_, that_CST both_DB2 known_VVN and_CC unknown_JJ determinants_NN2 of_IO outcome_NN1 are_VBR evenly_RR distributed_VVN between_II treatment_NN1 and_CC control_NN1 groups_NN2 ._. <p>_NULL 
</s>
<s>
What_DDQ can_VM the_AT clinician_NN1 do_VDI if_CS no_PN121 one_PN122 has_VHZ done_VDN a_AT1 randomized_JJ trial_NN1 of_IO the_AT therapeutic_JJ question_NN1 she_PPHS1 faces_VVZ ?_? 
</s>
<s>
She_PPHS1 still_RR has_VHZ to_TO make_VVI a_AT1 treatment_NN1 decision_NN1 ,_, and_CC so_RR must_VM rely_VVI on_II weaker_JJR studies_NN2 ._. 
</s>
<s>
In_II a_AT1 later_JJR article_NN1 in_II this_DD1 series_NN devoted_JJ to_II deciding_VVG whether_CSW a_AT1 therapy_NN1 or_CC an_AT1 exposure_NN1 causes_VVZ harm_NN1 (_( a_AT1 situation_NN1 when_CS randomization_NN1 is_VBZ usually_RR not_XX possible_JJ )_) we_PPIS2 deal_VV0 with_IW how_RRQ to_TO assess_VVI weaker_JJR study_NN1 designs_NN2 ._. 
</s>
<s>
For_IF now_RT ,_, you_PPY should_VM bear_VVI in_II mind_NN1 that_CST non-randomized_JJ studies_NN2 provide_VV0 much_RR weaker_JJR evidence_NN1 than_CSN do_VD0 randomized_JJ trials._NNU <h>_NULL 2_MC ._. 
</s>
<s>
Were_VBDR all_DB patients_NN2 who_PNQS entered_VVD the_AT trial_NN1 properly_RR accounted_VVN for_IF and_CC attributed_VVN at_II its_APPGE conclusion_NN1 ?_? <p>_NULL 
</s>
<s>
This_DD1 guide_NN1 has_VHZ two_MC components_NN2 :_: was_VBDZ followup_NN1 complete_VV0 ?_? and_CC ,_, were_VBDR patients_NN2 analyzed_VVD in_II the_AT groups_NN2 to_II which_DDQ they_PPHS2 were_VBDR randomized_VVN ?_? <h>_NULL a_ZZ1 )_) Was_VBDZ followup_NN1 complete_VV0 ?_? <p>_NULL 
</s>
<s>
Every_AT1 patient_NN1 who_PNQS entered_VVD the_AT trial_NN1 should_VM be_VBI accounted_VVN for_IF at_II its_APPGE conclusion_NN1 ._. 
</s>
<s>
If_CS this_DD1 is_VBZ not_XX done_VDN ,_, or_CC if_CS substantial_JJ numbers_NN2 of_IO patients_NN2 are_VBR reported_VVN as_CSA "_" lost_VVN to_TO followup_VVI ,_, "_" the_AT validity_NN1 of_IO the_AT study_NN1 is_VBZ open_JJ to_II question_NN1 ._. 
</s>
<s>
The_AT greater_JJR the_AT number_NN1 of_IO subjects_NN2 who_PNQS are_VBR lost_VVN ,_, the_AT more_RRR the_AT trial_NN1 may_VM be_VBI subject_II21 to_II22 bias_NN1 because_CS patients_NN2 who_PNQS are_VBR lost_VVN often_RR have_VH0 different_JJ prognoses_NN2 from_II those_DD2 who_PNQS are_VBR retained_VVN ,_, and_CC may_VM disappear_VVI because_CS they_PPHS2 suffer_VV0 adverse_JJ outcomes_NN2 (_( even_RR death_NN1 )_) or_CC because_CS they_PPHS2 are_VBR doing_VDG well_RR (_( and_CC so_RR did_VDD not_XX return_VVI to_II clinic_NN1 to_TO be_VBI assessed_VVN )_) ._. <p>_NULL 
</s>
<s>
Readers_NN2 can_VM decide_VVI for_IF themselves_PPX2 when_CS the_AT loss_NN1 to_II follow-up_NN1 is_VBZ excessive_JJ by_II assuming_VVG ,_, in_II positive_JJ trials_NN2 ,_, that_CST all_DB patients_NN2 lost_VVN from_II the_AT treatment_NN1 group_NN1 did_VDD badly_RR ,_, and_CC all_DB lost_VVN from_II the_AT control_NN1 group_NN1 did_VDD well_RR ,_, and_CC then_RT recalculating_VVG the_AT outcomes_NN2 under_II these_DD2 assumptions_NN2 ._. 
</s>
<s>
If_CS the_AT conclusions_NN2 of_IO the_AT trial_NN1 do_VD0 not_XX change_VVI ,_, then_RT the_AT loss_NN1 to_II follow-up_NN1 was_VBDZ not_XX excessive_JJ ._. 
</s>
<s>
If_CS the_AT conclusions_NN2 would_VM change_VVI ,_, the_AT strength_NN1 of_IO inference_NN1 is_VBZ weakened_VVN (_( that_REX21 is_REX22 ,_, less_DAR confidence_NN1 can_VM be_VBI placed_VVN in_II the_AT study_NN1 results_NN2 )_) ._. 
</s>
<s>
The_AT extent_NN1 to_II which_DDQ the_AT inference_NN1 is_VBZ weakened_VVN will_VM depend_VVI on_II how_RGQ likely_RR it_PPH1 is_VBZ that_DD1 treatment_NN1 patients_NN2 lost_VVD to_TO followup_VVI all_DB did_VDD badly_RR ,_, while_CS control_NN1 patients_NN2 lost_VVD to_TO followup_VVI all_DB did_VDD well._NNU <h>_NULL b_ZZ1 )_) Were_VBDR patients_NN2 analyzed_VVD in_II the_AT groups_NN2 to_II which_DDQ they_PPHS2 were_VBDR randomized_VVN ?_? <p>_NULL 
</s>
<s>
As_CSA in_II routine_NN1 practice_NN1 ,_, patients_NN2 in_II randomized_JJ trials_NN2 sometimes_RT forget_VV0 to_TO take_VVI their_APPGE medicine_NN1 or_CC even_RR refuse_VV0 their_APPGE treatment_NN1 altogether_RR ._. 
</s>
<s>
Readers_NN2 might_VM ,_, on_II first_MD blush_NN1 ,_, agree_VV0 that_CST such_DA patients_NN2 who_PNQS never_RR actually_RR received_VVD their_APPGE assigned_JJ treatment_NN1 should_VM be_VBI excluded_VVN from_II analyses_NN2 for_IF efficacy_NN1 ._. 
</s>
<s>
Not_XX so_RR ._. <p>_NULL 
</s>
<s>
The_AT reasons_NN2 people_NN do_VD0 n't_XX take_VVI their_APPGE medication_NN1 are_VBR often_RR related_VVN to_II prognosis_NN1 ._. 
</s>
<s>
In_II a_AT1 number_NN1 of_IO randomized_JJ trials_NN2 non-compliant_JJ patients_NN2 have_VH0 fared_VVN worse_RRR than_CSN those_DD2 who_PNQS took_VVD their_APPGE medication_NN1 as_CSA instructed_VVN ,_, even_RR after_II taking_VVG into_II account_NN1 all_RR known_VVN prognostic_JJ factors_NN2 ,_, and_CC even_CS21 when_CS22 their_APPGE medications_NN2 were_VBDR placebos_NN2 !_! &lsqb;_( 14_MC &rsqb;_) &lsqb;_( 15_MC &rsqb;_) &lsqb;_( 16_MC &rsqb;_) &lsqb;_( 17_MC &rsqb;_) &lsqb;_( 18_MC &rsqb;_) &lsqb;_( 19_MC &rsqb;_) Excluding_II non-compliant_JJ patients_NN2 from_II the_AT analysis_NN1 leaves_VVZ behind_II those_DD2 who_PNQS may_VM be_VBI destined_VVN to_TO have_VHI a_AT1 better_JJR outcome_NN1 and_CC destroys_VVZ the_AT unbiased_JJ comparison_NN1 provided_VVN by_II randomization_NN1 ._. <p>_NULL 
</s>
<s>
The_AT situation_NN1 is_VBZ similar_JJ with_IW surgical_JJ therapies_NN2 ._. 
</s>
<s>
Some_DD patients_NN2 randomized_VVD to_II surgery_NN1 never_RR have_VH0 the_AT operation_NN1 because_CS they_PPHS2 are_VBR too_RG sick_JJ ,_, or_CC suffer_VV0 the_AT outcome_NN1 of_IO interest_NN1 (_( such_II21 as_II22 stroke_NN1 or_CC myocardial_JJ infarction_NN1 )_) before_CS they_PPHS2 get_VV0 to_II the_AT operating_NN1 room_NN1 ._. 
</s>
<s>
If_CS investigators_NN2 include_VV0 such_DA patients_NN2 ,_, who_PNQS are_VBR destined_VVN to_TO do_VDI badly_RR ,_, in_II the_AT control_NN1 arm_NN1 but_CCB not_XX in_II the_AT surgical_JJ arm_NN1 of_IO a_AT1 trial_NN1 ,_, even_RR a_AT1 useless_JJ surgical_JJ therapy_NN1 will_VM appear_VVI to_TO be_VBI effective_JJ ._. 
</s>
<s>
However_RR ,_, the_AT apparent_JJ effectiveness_NN1 of_IO surgery_NN1 will_VM come_VVI not_XX from_II a_AT1 benefit_NN1 to_II those_DD2 who_PNQS have_VH0 surgery_NN1 ,_, but_CCB the_AT systematic_JJ exclusion_NN1 of_IO those_DD2 with_IW the_AT poorest_JJT prognosis_NN1 from_II the_AT surgical_JJ group_NN1 ._. <p>_NULL 
</s>
<s>
This_DD1 principle_NN1 of_IO attributing_VVG all_DB patients_NN2 to_II the_AT group_NN1 to_II which_DDQ they_PPHS2 were_VBDR randomized_JJ results_NN2 in_II an_AT1 "_" intention-to-treat_JJ "_" analysis_NN1 ._. 
</s>
<s>
This_DD1 strategy_NN1 preserves_VVZ the_AT value_NN1 of_IO randomization_NN1 :_: prognostic_JJ factors_NN2 that_CST we_PPIS2 know_VV0 about_II ,_, and_CC those_DD2 we_PPIS2 do_VD0 n't_XX know_VVI about_II ,_, will_VM be_VBI ,_, on_II average_NN1 ,_, equally_RR distributed_VVN in_II the_AT two_MC groups_NN2 ,_, and_CC the_AT effect_NN1 we_PPIS2 see_VV0 will_VM be_VBI just_RR that_CST due_II21 to_II22 the_AT treatment_NN1 assigned_VVN ._. 
</s>
<s>
<h>_NULL B._NP1 Secondary_JJ Guides_NN2 <p>_NULL 
</s>
<s>
Patients_NN2 who_PNQS know_VV0 that_CST they_PPHS2 are_VBR on_II a_AT1 new_JJ ,_, experimental_JJ treatment_NN1 are_VBR likely_JJ to_TO have_VHI an_AT1 opinion_NN1 about_II its_APPGE efficacy_NN1 ,_, as_CSA are_VBR their_APPGE clinicians_NN2 or_CC the_AT other_JJ study_NN1 personnel_NN2 who_PNQS are_VBR measuring_VVG responses_NN2 to_II therapy_NN1 ._. 
</s>
<s>
These_DD2 opinions_NN2 ,_, whether_CSW optimistic_JJ or_CC pessimistic_JJ ,_, can_VM systematically_RR distort_VVI both_DB2 the_AT other_JJ aspects_NN2 of_IO treatment_NN1 ,_, and_CC the_AT reporting_NN1 of_IO treatment_NN1 outcomes_NN2 ,_, thereby_RR reducing_VVG our_APPGE confidence_NN1 in_II the_AT study_NN1 's_GE results_NN2 ._. 
</s>
<s>
In_RR21 addition_RR22 ,_, unblinded_JJ study_NN1 personnel_NN2 who_PNQS are_VBR measuring_VVG outcomes_NN2 may_VM provide_VVI different_JJ interpretations_NN2 of_IO marginal_JJ findings_NN2 or_CC differential_JJ encouragement_NN1 during_II performance_NN1 tests_NN2 ,_, either_RR one_MC1 of_IO which_DDQ can_VM distort_VVI their_APPGE results_NN2 &lsqb;_( 20_MC &rsqb;_) ._. <p>_NULL 
</s>
<s>
The_AT best_JJT way_NN1 of_IO avoiding_VVG all_DB this_DD1 bias_NN1 is_VBZ double-blinding_JJ (_( sometimes_RT referred_VVN to_II as_RG double-masking_JJ )_) ,_, which_DDQ is_VBZ achieved_VVN in_II drug_NN1 trials_NN2 by_II administering_VVG a_AT1 placebo_NN1 ,_, indistinguishable_JJ from_II active_JJ treatment_NN1 in_II appearance_NN1 ,_, taste_NN1 and_CC texture_NN1 but_CCB lacking_VVG the_AT putative_JJ active_JJ ingredient_NN1 ,_, to_II the_AT control_NN1 group_NN1 ._. 
</s>
<s>
When_CS you_PPY read_VV0 reports_NN2 on_II treatments_NN2 (_( such_II21 as_II22 trials_NN2 of_IO surgical_JJ therapies_NN2 )_) in_II which_DDQ patients_NN2 and_CC treating_VVG clinicians_NN2 can_VM not_XX be_VBI kept_VVN blind_JJ ,_, you_PPY should_VM note_VVI whether_CSW investigators_NN2 have_VH0 minimized_VVN bias_NN1 by_II blinding_VVG those_DD2 who_PNQS assess_VV0 clinical_JJ outcomes._NNU <h>_NULL 4_MC ._. 
</s>
<s>
Were_VBDR the_AT groups_NN2 similar_JJ at_II the_AT start_NN1 of_IO the_AT trial_NN1 ?_? <p>_NULL 
</s>
<s>
For_IF reassurance_NN1 about_II a_AT1 study_NN1 's_GE validity_NN1 ,_, readers_NN2 would_VM like_VVI to_TO be_VBI informed_VVN that_CST the_AT treatment_NN1 and_CC control_NN1 groups_NN2 were_VBDR similar_JJ for_IF all_DB the_AT factors_NN2 that_CST determine_VV0 the_AT clinical_JJ outcomes_NN2 of_IO interest_NN1 save_II one_MC1 :_: whether_CSW they_PPHS2 received_VVD the_AT experimental_JJ therapy_NN1 ._. 
</s>
<s>
Investigators_NN2 provide_VV0 this_DD1 reassurance_NN1 when_CS they_PPHS2 display_VV0 the_AT "_" entry_NN1 "_" or_CC "_" baseline_NN1 "_" prognostic_JJ features_NN2 of_IO the_AT treatment_NN1 and_CC control_NN1 patients_NN2 ._. 
</s>
<s>
Although_CS we_PPIS2 never_RR will_VM know_VVI whether_CSW similarity_NN1 exists_VVZ for_IF the_AT unknown_JJ prognostic_JJ factors_NN2 ,_, we_PPIS2 are_VBR reassured_VVN when_CS the_AT known_JJ prognostic_JJ factors_NN2 are_VBR nicely_RR balanced_VVN ._. 
</s>
<s>
Randomization_NN1 does_VDZ n't_XX always_RR produce_VVI groups_NN2 balanced_VVN for_IF known_JJ prognostic_JJ factors_NN2 ._. 
</s>
<s>
When_CS the_AT groups_NN2 are_VBR small_JJ ,_, chance_NN1 may_VM place_VVI those_DD2 with_IW apparently_RR better_JJR prognoses_NN2 in_II one_MC1 group_NN1 ._. 
</s>
<s>
As_CSA sample_NN1 size_NN1 increases_NN2 ,_, this_DD1 is_VBZ less_RGR and_CC less_RGR likely_JJ (_( this_DD1 is_VBZ analogous_JJ to_II multiple_JJ coin_NN1 flips_VVZ :_: one_PN1 would_VM n't_XX be_VBI too_RG surprised_JJ to_TO see_VVI seven_MC heads_NN2 out_II21 of_II22 ten_MC coin_NN1 flips_VVZ ,_, but_CCB one_PN1 would_VM be_VBI very_RG surprised_JJ to_TO see_VVI seventy_MC heads_NN2 out_II21 of_II22 one_MC1 hundred_NNO coin_NN1 flips_VVZ )_) ._. <p>_NULL 
</s>
<s>
The_AT issue_NN1 here_RL is_VBZ not_XX whether_CSW there_EX are_VBR statistically_RR significant_JJ differences_NN2 in_II known_JJ prognostic_JJ factors_NN2 between_II treatment_NN1 groups_NN2 (_( in_II a_AT1 randomized_JJ trial_NN1 one_PN1 knows_VVZ in_II advance_NN1 that_CST any_DD differences_NN2 that_CST did_VDD occur_VVI happened_VVN by_II chance_NN1 )_) but_CCB rather_RR the_AT magnitude_NN1 of_IO these_DD2 differences_NN2 ._. 
</s>
<s>
If_CS they_PPHS2 are_VBR large_JJ ,_, the_AT validity_NN1 of_IO the_AT study_NN1 may_VM be_VBI compromised_VVN ._. 
</s>
<s>
The_AT stronger_JJR the_AT relationship_NN1 between_II the_AT prognostic_JJ factors_NN2 and_CC outcome_NN1 ,_, and_CC the_AT smaller_JJR the_AT trial_NN1 ,_, the_AT more_RRR the_AT differences_NN2 between_II groups_NN2 will_VM weaken_VVI the_AT strength_NN1 of_IO any_DD inference_NN1 about_II efficacy_NN1 ._. <p>_NULL 
</s>
<s>
All_DB is_VBZ not_XX lost_VVN if_CS the_AT treatment_NN1 groups_NN2 are_VBR not_XX similar_JJ at_II baseline_NN1 ._. 
</s>
<s>
Statistical_JJ techniques_NN2 permit_VV0 adjustment_NN1 of_IO the_AT study_NN1 result_NN1 for_IF baseline_NN1 differences_NN2 ._. 
</s>
<s>
Accordingly_RR ,_, readers_NN2 should_VM look_VVI for_IF documentation_NN1 of_IO similarity_NN1 for_IF relevant_JJ baseline_NN1 characteristics_NN2 ,_, and_CC if_CS substantial_JJ differences_NN2 exist_VV0 should_VM note_VVI whether_CSW the_AT investigators_NN2 conducted_VVD an_AT1 analysis_NN1 that_CST adjusted_VVD for_IF those_DD2 differences_NN2 ._. 
</s>
<s>
When_CS both_DB2 unadjusted_JJ and_CC adjusted_JJ analyses_NN2 reach_VV0 the_AT same_DA conclusion_NN1 ,_, readers_NN2 justifiably_RR gain_VV0 confidence_NN1 in_II the_AT validity_NN1 of_IO the_AT study_NN1 result._NNU <h>_NULL 5_MC ._. 
</s>
<s>
Aside_II21 from_II22 the_AT experimental_JJ intervention_NN1 ,_, were_VBDR the_AT groups_NN2 treated_VVN equally_RR ?_? <p>_NULL 
</s>
<s>
Care_VV0 for_IF experimental_JJ and_CC control_NN1 groups_NN2 can_VM differ_VVI in_II a_AT1 number_NN1 of_IO ways_NN2 besides_II the_AT test_NN1 therapy_NN1 ,_, and_CC differences_NN2 in_II care_NN1 other_II21 than_II22 that_DD1 under_II study_NN1 can_VM weaken_VVI distort_VV0 the_AT results_NN2 ._. 
</s>
<s>
If_CS one_MC1 group_NN1 received_VVD closer_JJR followup_NN1 ,_, events_NN2 might_VM be_VBI more_RGR likely_JJ to_TO be_VBI reported_VVN ,_, and_CC patients_NN2 may_VM be_VBI treated_VVN more_RGR intensively_RR with_IW non-study_JJ therapies_NN2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, in_II trials_NN2 of_IO new_JJ forms_NN2 of_IO therapy_NN1 for_IF resistant_JJ rheumatoid_JJ arthritis_NN1 ,_, ancillary_JJ treatment_NN1 with_IW systemic_JJ steroids_NN2 (_( extremely_RR effective_JJ for_IF relieving_JJ symptoms_NN2 )_) ,_, if_CS administered_VVN more_RGR frequently_RR to_II the_AT control_NN1 group_NN1 than_CSN to_II the_AT treatment_NN1 group_NN1 ,_, could_VM obscure_VVI an_AT1 experimental_JJ drug_NN1 's_GE true_JJ treatment_NN1 effect_NN1 (_( unless_CS exacerbation_NN1 requiring_VVG steroids_NN2 were_VBDR itself_PPX1 counted_VVN as_II an_AT1 outcome_NN1 )_) ._. <p>_NULL 
</s>
<s>
Interventions_NN2 other_II21 than_II22 the_AT treatment_NN1 under_II study_NN1 ,_, when_CS differentially_RR applied_VVN to_II the_AT treatment_NN1 and_CC control_NN1 groups_NN2 ,_, often_RR are_VBR called_VVN "_" cointerventions_NN2 "_" ._. 
</s>
<s>
Cointervention_NN1 is_VBZ a_AT1 more_RGR serious_JJ problem_NN1 when_CS double-blinding_NN1 is_VBZ absent_JJ ,_, or_CC when_CS the_AT use_NN1 of_IO very_RG effective_JJ non-study_JJ treatments_NN2 is_VBZ permitted_VVN at_II the_AT physicians_58 '_GE discretion_NN1 ._. 
</s>
<s>
Clinicians_NP1 gain_NN1 greatest_JJT confidence_NN1 in_II the_AT results_NN2 when_RRQ permissible_JJ cointerventions_NN2 are_VBR described_VVN in_II the_AT methods_NN2 section_NN1 and_CC documented_VVN to_TO be_VBI infrequent_JJ occurrences_NN2 in_II the_AT results_NN2 ._. <p>_NULL 
</s>
<s>
The_AT foregoing_JJ five_MC guides_NN2 (_( two_MC primary_JJ and_CC three_MC secondary_JJ )_) ,_, applied_VVN in_II sequence_NN1 ,_, will_VM help_VVI the_AT reader_NN1 determine_VV0 whether_CSW the_AT results_NN2 of_IO an_AT1 article_NN1 on_II therapy_NN1 are_VBR likely_JJ to_TO be_VBI valid_JJ ._. 
</s>
<s>
If_CS the_AT results_NN2 are_VBR valid_JJ ,_, then_RT the_AT reader_NN1 can_VM proceed_VVI to_TO consider_VVI the_AT magnitude_NN1 of_IO the_AT effect_NN1 and_CC the_AT applicability_NN1 to_II her_APPGE patients_NN2 ._. <p>_NULL 
</s>
<s>
Scenario_NN1 Resolution_NN1 <p>_NULL 
</s>
<s>
Readers_NN2 may_VM be_VBI interested_JJ in_II how_RGQ well_RR the_AT trial_NN1 of_IO plasmapheresis_NN1 in_II patients_NN2 with_IW lupus_NN1 nephritis_NN1 met_VVD the_AT tests_NN2 of_IO validity_NN1 ._. 
</s>
<s>
With_II31 respect_II32 to_II33 primary_JJ criteria_NN2 ,_, randomization_NN1 was_VBDZ rigorously_RR conducted_VVN ,_, as_CSA treatment_NN1 was_VBDZ assigned_VVN through_II a_AT1 phone_NN1 call_NN1 to_II the_AT study_NN1 's_GE Methods_NN2 Center_NN1 ._. 
</s>
<s>
One_MC1 patient_NN1 assigned_VVN to_II standard_JJ therapy_NN1 was_VBDZ lost_VVN to_TO followup_VVI ,_, and_CC all_DB the_AT other_JJ patients_NN2 were_VBDR analyzed_VVN in_II the_AT group_NN1 to_II which_DDQ they_PPHS2 had_VHD been_VBN assigned_VVN ._. 
</s>
<s>
With_II31 respect_II32 to_II33 secondary_JJ criteria_NN2 ,_, the_AT study_NN1 was_VBDZ not_XX blinded_VVN ,_, the_AT two_MC groups_NN2 were_VBDR comparable_JJ at_II the_AT start_NN1 of_IO the_AT trial_NN1 ,_, and_CC the_AT authors_NN2 provide_VV0 little_JJ information_NN1 about_II comparability_NN1 of_IO other_JJ treatments_NN2 ._. <p>_NULL 
</s>
<s>
In_II the_AT introductory_JJ paper_NN1 in_II this_DD1 series_NN ,_, we_PPIS2 described_VVD the_AT concept_NN1 of_IO strength_NN1 of_IO inference_NN1 ._. 
</s>
<s>
The_AT final_JJ assessment_NN1 of_IO validity_NN1 is_VBZ never_RR a_AT1 "_" yes_UH "_" or_CC "_" no_AT "_" decision_NN1 and_CC must_VM ,_, to_II some_DD extent_NN1 ,_, be_VBI subjective_JJ ._. 
</s>
<s>
We_PPIS2 judge_VV0 that_CST the_AT methods_NN2 in_II this_DD1 trial_NN1 were_VBDR ,_, overall_RR ,_, strong_JJ ,_, and_CC provide_VV0 a_AT1 valid_JJ start_NN1 for_IF deciding_VVG whether_CSW31 or_CSW32 not_CSW33 to_TO administer_VVI plasmapheresis_NN1 to_II our_APPGE patient_NN1 with_IW severe_JJ lupus_NN1 nephritis_NN1 ._. 
</s>
<s>
<h>_NULL II_MC ._. 
</s>
<s>
What_DDQ were_VBDR the_AT results_NN2 ?_? <p>_NULL 
</s>
<s>
Clinical_JJ Scenario_NN1 <p>_NULL 
</s>
<s>
You_PPY are_VBR a_AT1 general_JJ internist_NN1 who_PNQS is_VBZ asked_VVN to_TO see_VVI a_AT1 65_MC year-old_JJ man_NN1 with_IW controlled_JJ hypertension_NN1 and_CC a_AT1 six-month_JJ history_NN1 of_IO atrial_JJ fibrillation_NN1 resistant_JJ to_II cardioversion_NN1 ._. 
</s>
<s>
Although_CS he_PPHS1 has_VHZ no_AT evidence_NN1 for_IF valvular_JJ or_CC coronary_JJ heart_NN1 disease_NN1 ,_, the_AT family_NN1 physician_NN1 who_PNQS referred_VVD him_PPHO1 to_II you_PPY wants_VVZ your_APPGE advice_NN1 on_II whether_CSW the_AT benefits_NN2 of_IO long-term_JJ anticoagulants_NN2 (_( to_TO reduce_VVI the_AT risk_NN1 of_IO embolic_JJ stroke_NN1 )_) outweigh_VV0 their_APPGE risks_NN2 (_( of_IO hemorrhage_NN1 from_II anticoagulant_JJ therapy_NN1 )_) ._. 
</s>
<s>
The_AT patient_JJ shares_NN2 these_DD2 concerns_NN2 ,_, and_CC does_VDZ n't_XX want_VVI to_TO receive_VVI a_AT1 treatment_NN1 that_CST would_VM do_VDI more_DAR harm_NN1 than_CSN good_JJ ._. 
</s>
<s>
You_PPY know_VV0 that_CST there_EX have_VH0 been_VBN randomized_VVN trials_NN2 of_IO warfarin_NN1 for_IF non-valvular_JJ atrial_JJ fibrillation_NN1 ,_, and_CC decide_VV0 that_CST you_PPY 'd_VHD better_RRR review_VVI one_MC1 of_IO them_PPHO2 ._. <p>_NULL 
</s>
<s>
The_AT Search_NN1 <p>_NULL 
</s>
<s>
The_AT ideal_JJ article_NN1 addressing_VVG this_DD1 clinical_JJ problem_NN1 would_VM include_VVI patients_NN2 with_IW non-valvular_JJ atrial_JJ fibrillation_NN1 ,_, and_CC would_VM compare_VVI the_AT effect_NN1 of_IO warfarin_NN1 and_CC a_AT1 control_NN1 treatment_NN1 ,_, ideally_RR a_AT1 placebo_NN1 ,_, on_II the_AT risk_NN1 of_IO emboli_NN2 (_( including_II embolic_JJ stroke_NN1 )_) and_CC also_RR on_II the_AT risk_NN1 of_IO the_AT complications_NN2 of_IO anticoagulation_NN1 ._. 
</s>
<s>
Randomized_NP1 ,_, double-blind_JJ studies_NN2 would_VM provide_VVI the_AT strongest_JJT evidence_NN1 ._. <p>_NULL 
</s>
<s>
In_II the_AT software_NN1 program_NN1 "_" Grateful_JJ Med_JJ "_" you_PPY select_VV0 a_AT1 Medical_JJ subject_NN1 (_( MeSH_NN1 )_) heading_VVG that_CST identifies_VVZ your_APPGE population_NN1 ,_, "_" atrial_JJ fibrillation_NN1 ,_, "_" another_DD1 that_CST specifies_VVZ the_AT intervention_NN1 ,_, "_" warfarin_NN1 "_" ,_, and_CC a_AT1 third_MD that_DD1 specifies_VVZ the_AT outcome_NN1 of_IO interest_NN1 ,_, "_" stroke_NN1 "_" (_( which_DDQ the_AT software_NN1 automatically_RR converts_VVZ to_TO "_" explode_VVI cerebrovascular_JJ disorders_NN2 "_" meaning_VVG that_CST all_DB articles_NN2 indexed_VVN under_II cerebrovascular_JJ disorders_NN2 or_CC its_APPGE subheadings_NN2 are_VBR potential_JJ targets_NN2 of_IO the_AT search_NN1 )_) ,_, while_CS restricting_VVG the_AT search_NN1 to_II English-language_JJ studies_NN2 ._. 
</s>
<s>
To_TO ensure_VVI that_DD1 ,_, at_RR21 least_RR22 on_II your_APPGE first_MD pass_NN1 ,_, you_PPY identify_VV0 only_RR the_AT highest_JJT quality_NN1 studies_NN2 ,_, you_PPY include_VV0 the_AT methodological_JJ term_NN1 "_" randomized_VVD controlled_JJ trial_NN1 (_( PT_FO )_) "_" (_( PT_NN1 stands_VVZ for_IF publication_NN1 type_NN1 )_) ._. 
</s>
<s>
The_AT search_NN1 yields_VVZ nine_MC articles_NN2 ._. 
</s>
<s>
Three_MC are_VBR editorials_NN2 or_CC commentaries_NN2 ,_, one_PN1 addresses_VVZ prognosis_NN1 ,_, and_CC one_PN1 focuses_VVZ on_II quality_NN1 of_IO life_NN1 on_II anticoagulants_NN2 ._. 
</s>
<s>
You_PPY decide_VV0 to_TO read_VVI the_AT most_RGT recent_JJ of_IO the_AT four_MC randomized_JJ trials_NN2 &lsqb;_( 21_MC &rsqb;_) ._. <p>_NULL 
</s>
<s>
Reading_VVG the_AT study_NN1 ,_, you_PPY find_VV0 it_PPH1 meets_VVZ the_AT validity_NN1 criteria_NN2 you_PPY learned_VVD about_RP in_II a_AT1 prior_JJ article_NN1 in_II this_DD1 series_NN &lsqb;_( 22_MC &rsqb;_) ._. 
</s>
<s>
To_TO answer_VVI your_APPGE patient_NN1 's_GE and_CC the_AT referring_VVG physician_NN1 's_GE concerns_NN2 ,_, however_RR ,_, you_PPY need_VV0 to_TO delve_VVI further_RRR into_II the_AT relation_NN1 between_II benefits_NN2 and_CC risks._NNU <h>_NULL 1_MC1 ._. 
</s>
<s>
How_RGQ large_JJ was_VBDZ the_AT treatment_NN1 effect_NN1 ?_? <p>_NULL 
</s>
<s>
Most_RGT frequently_RR ,_, randomized_VVD clinical_JJ trials_NN2 carefully_RR monitor_VV0 how_RGQ often_RR patients_NN2 experience_VV0 some_DD adverse_JJ event_NN1 or_CC outcome_NN1 ._. 
</s>
<s>
Examples_NN2 of_IO these_DD2 "_" dichotomous_JJ "_" outcomes_NN2 (_( "_" yes_UH "_" or_CC "_" no_AT "_" outcomes_NN2 that_CST either_RR happen_VV0 or_CC do_VD0 n't_XX happen_VVI )_) include_VV0 cancer_NN1 recurrence_NN1 ,_, myocardial_JJ infarction_NN1 ,_, and_CC death_NN1 ._. 
</s>
<s>
Patients_NN2 either_RR do_VD0 or_CC do_VD0 not_XX suffer_VVI an_AT1 event_NN1 ,_, and_CC the_AT article_NN1 reports_VVZ the_AT proportion_NN1 of_IO patients_NN2 who_PNQS develop_VV0 such_DA events_NN2 ._. 
</s>
<s>
Consider_VV0 ,_, for_REX21 example_REX22 ,_, a_AT1 study_NN1 in_II which_DDQ 20%_NNU (_( 0.20_MC )_) of_IO a_AT1 control_NN1 group_NN1 died_VVD ,_, but_CCB only_RR 15%_NNU (_( 0.15_MC )_) of_IO those_DD2 receiving_VVG a_AT1 new_JJ treatment_NN1 died_VVD ._. 
</s>
<s>
How_RRQ might_VM these_DD2 results_NN2 be_VBI expressed_VVN ?_? 
</s>
<s>
Table_NN1 2_MC provides_VVZ a_AT1 summary_NN1 of_IO ways_NN2 of_IO presenting_VVG the_AT effects_NN2 of_IO therapy_NN1 ._. 
</s>
<s>
<h>_NULL Table_NN1 2_MC :_: Measures_NN2 of_IO the_AT effects_NN2 of_IO therapy_NN1 <p>_NULL 
</s>
<s>
Risk_VV0 without_IW therapy_NN1 (_( Baseline_NN1 risk_NN1 )_) :_: X_ZZ1 <p>_NULL 
</s>
<s>
20/100=0.20_FU or_CC 20%_NNU <p>_NULL 
</s>
<s>
Risk_VV0 with_IW therapy_NN1 :_: Y_ZZ1 <p>_NULL 
</s>
<s>
15/100=0.15_FU or_CC 15%_NNU <p>_NULL 
</s>
<s>
Absolute_JJ Risk_NN1 Reduction_NN1 (_( Risk_VV0 Difference_NN1 )_) :_: X_ZZ1 -_- Y_ZZ1 <p>_NULL 
</s>
<s>
0.20-0.15=0.05_FO <p>_NULL 
</s>
<s>
Relative_JJ Risk_NN1 :_: Y/X_ZZ1 <p>_NULL 
</s>
<s>
0.15/0.20_MF =_FO 0.75_MC <p>_NULL 
</s>
<s>
Relative_JJ Risk_NN1 Reduction_NN1 (_( RRR_NP1 )_) :_: &lsqb;_( 1-Y/X_FU &rsqb;_) x_ZZ1 100_MC or_CC &lsqb;_( (_( X-Y_FO )_) /_FO X_ZZ1 &rsqb;_) x_ZZ1 100_MC <p>_NULL 
</s>
<s>
&lsqb;_( 1-0.75_MCMC &rsqb;_) x100=25%_FO &lsqb;_( 0.05/0.20_MF &rsqb;_) x100=25%_FO <p>_NULL 
</s>
<s>
95%_NNU Confidence_NN1 Interval_NN1 for_IF the_AT RRR_NP1 <p>_NULL 
</s>
<s>
-38%_FO to_II +59%_FO <p>_NULL 
</s>
<s>
One_MC1 way_NN1 would_VM be_VBI as_II the_AT absolute_JJ difference_NN1 (_( known_VVN as_II the_AT absolute_JJ risk_NN1 reduction_NN1 ,_, or_CC risk_NN1 difference_NN1 )_) ,_, between_II the_AT proportion_NN1 who_PNQS died_VVD in_II the_AT control_NN1 group_NN1 (_( X_ZZ1 )_) and_CC the_AT proportion_NN1 who_PNQS died_VVD in_II the_AT treatment_NN1 group_NN1 (_( Y_ZZ1 )_) ,_, or_CC X_ZZ1 -_- Y_ZZ1 =_FO 0.20_MC -_- 0.15_MC =_FO 0.05_MC ._. 
</s>
<s>
Another_DD1 way_NN1 to_TO express_VVI the_AT impact_NN1 of_IO treatment_NN1 would_VM be_VBI as_II a_AT1 relative_JJ risk_NN1 :_: the_AT risk_NN1 of_IO events_NN2 among_II patients_NN2 on_II the_AT new_JJ treatment_NN1 ,_, relative_II21 to_II22 that_DD1 among_II controls_NN2 ,_, or_CC Y/X_ZZ1 =_FO 0.15_MC /_FO 0.20_MC =_FO 0.75_MC ._. <p>_NULL 
</s>
<s>
The_AT most_RGT commonly_RR reported_VVN measure_NN1 of_IO dichotomous_JJ treatment_NN1 effects_NN2 is_VBZ the_AT complement_NN1 of_IO this_DD1 relative_JJ risk_NN1 ,_, and_CC is_VBZ called_VVN the_AT relative_JJ risk_NN1 reduction_NN1 (_( RRR_NP1 )_) ._. 
</s>
<s>
It_PPH1 is_VBZ expressed_VVN as_II a_AT1 per_NNU21 cent_NNU22 :_: (_( 1_MC1 -_- Y/X_ZZ1 )_) x_ZZ1 100%_NNU =_FO (_( 1_MC1 -_- 0.75_MC )_) x_ZZ1 100%_NNU =_FO 25%_NNU ._. 
</s>
<s>
A_ZZ1 RRR_NP1 of_IO 25%_NNU means_VVZ that_CST the_AT new_JJ treatment_NN1 reduced_VVD the_AT risk_NN1 of_IO death_NN1 by_II 25%_NNU relative_II21 to_II22 that_DD1 occurring_VVG among_II control_NN1 patients_NN2 ;_; the_AT greater_JJR the_AT relative_JJ risk_NN1 reduction_NN1 ,_, the_AT more_RGR effective_JJ the_AT therapy._NNU <h>_NULL 2_MC ._. 
</s>
<s>
How_RGQ precise_JJ was_VBDZ the_AT estimate_NN1 of_IO treatment_NN1 effect_NN1 ?_? <p>_NULL 
</s>
<s>
The_AT true_JJ risk_NN1 reduction_NN1 can_VM never_RR be_VBI known_VVN ;_; all_DB we_PPIS2 have_VH0 is_VBZ the_AT estimate_NN1 provided_VVN by_II rigorous_JJ controlled_JJ trials_NN2 ,_, and_CC the_AT best_JJT estimate_NN1 of_IO the_AT true_JJ treatment_NN1 effect_NN1 is_VBZ that_CST observed_VVD in_II the_AT trial_NN1 ._. 
</s>
<s>
This_DD1 estimate_NN1 is_VBZ called_VVN a_AT1 "_" point_NN1 estimate_NN1 "_" in_BCL21 order_BCL22 to_TO remind_VVI us_PPIO2 that_CST ,_, although_CS the_AT true_JJ value_NN1 lies_VVZ somewhere_RL in_II its_APPGE neighbourhood_NN1 ,_, it_PPH1 is_VBZ unlikely_JJ to_TO be_VBI precisely_RR correct_JJ ._. 
</s>
<s>
Investigators_NN2 tell_VV0 us_PPIO2 the_AT neighbourhood_NN1 within_II which_DDQ the_AT true_JJ effect_NN1 likely_JJ lies_NN2 by_II the_AT statistical_JJ strategy_NN1 of_IO calculating_VVG confidence_NN1 intervals_NN2 &lsqb;_( 23_MC &rsqb;_) ._. <p>_NULL 
</s>
<s>
We_PPIS2 usually_RR (_( though_CS arbitrarily_RR )_) use_VV0 the_AT 95%_NNU confidence_NN1 interval_NN1 which_DDQ can_VM be_VBI simply_RR interpreted_VVN as_CSA defining_VVG the_AT range_NN1 that_CST includes_VVZ the_AT true_JJ relative_JJ risk_NN1 reduction_NN1 95%_NNU of_IO the_AT time_NNT1 ._. 
</s>
<s>
You_PPY 'll_VM seldom_RR find_VVI the_AT true_JJ RRR_NP1 toward_II the_AT extremes_NN2 of_IO this_DD1 interval_NN1 ,_, and_CC you_PPY 'll_VM find_VVI the_AT true_JJ RRR_NP1 beyond_II these_DD2 extremes_NN2 only_RR 5%_NNU of_IO the_AT time_NNT1 ,_, a_AT1 property_NN1 of_IO the_AT confidence_NN1 interval_NN1 that_CST relates_VVZ closely_RR to_II the_AT conventional_JJ level_NN1 of_IO "_" statistical_JJ significance_NN1 "_" of_IO p_ZZ1 &lt;_FO 0.05_MC ._. 
</s>
<s>
We_PPIS2 illustrate_VV0 the_AT use_NN1 of_IO confidence_NN1 intervals_NN2 in_II the_AT following_JJ examples_NN2 ._. <p>_NULL 
</s>
<s>
If_CS a_AT1 trial_NN1 randomized_VVD 100_MC patients_NN2 each_DD1 to_II treatment_NN1 and_CC control_NN1 groups_NN2 ,_, and_CC there_EX were_VBDR 20_MC deaths_NN2 in_II the_AT control_NN1 group_NN1 and_CC 15_MC deaths_NN2 in_II the_AT treatment_NN1 group_NN1 ,_, the_AT authors_NN2 would_VM calculate_VVI a_AT1 point_NN1 estimate_NN1 for_IF the_AT relative_JJ risk_NN1 reduction_NN1 of_IO 25%_NNU (_( X_ZZ1 =_FO 20/100_MF or_CC 0.20_MC ,_, Y_ZZ1 =_FO 15/100_MF or_CC 0.15_MC ,_, and_CC 1-Y/X_FU =_FO &lsqb;_( 1-0.75_MCMC &rsqb;_) x100_FO =_FO 25%_NNU )_) ._. 
</s>
<s>
You_PPY might_VM guess_VVI ,_, however_RR ,_, that_CST the_AT true_JJ relative_JJ risk_NN1 reduction_NN1 might_VM be_VBI much_RR smaller_JJR or_CC much_RR greater_JJR than_CSN this_DD1 25%_NNU ,_, based_VVN on_II a_AT1 difference_NN1 of_IO just_RR 5_MC deaths_NN2 ._. 
</s>
<s>
In_II fact_NN1 ,_, you_PPY surmise_VV0 that_CST the_AT treatment_NN1 might_VM provide_VVI no_AT benefit_NN1 (_( an_AT1 RRR_NP1 of_IO 0%_NNU )_) or_CC even_RR harm_VV0 (_( a_AT1 negative_JJ RRR_NP1 )_) ._. 
</s>
<s>
And_CC you_PPY would_VM be_VBI right_JJ --_NN1 in_II fact_NN1 ,_, these_DD2 results_NN2 are_VBR consistent_JJ with_IW both_RR an_AT1 RRR_NP1 of_IO -_- 38%_NNU (_( that_REX21 is_REX22 ,_, patients_NN2 given_VVN the_AT new_JJ treatment_NN1 might_VM be_VBI 38%_NNU more_DAR likely_JJ to_TO die_VVI than_CSN control_NN1 patients_NN2 )_) ,_, and_CC an_AT1 RRR_NP1 of_IO nearly_RR 59%_NNU (_( that_REX21 is_REX22 ,_, patients_NN2 subsequently_RR receiving_VVG the_AT new_JJ treatment_NN1 might_VM have_VHI a_AT1 risk_NN1 of_IO dying_VVG less_DAR than_CSN 60%_NNU that_DD1 of_IO the_AT risk_NN1 in_II those_DD2 who_PNQS are_VBR not_XX treated_VVN )_) ._. 
</s>
<s>
In_II other_JJ words_NN2 ,_, the_AT 95%_NNU confidence_NN1 interval_NN1 on_II this_DD1 RRR_NP1 is_VBZ -38%_FO to_II 59%_NNU ,_, and_CC the_AT trial_NN1 really_RR has_VHZ n't_XX helped_VVN us_PPIO2 decide_VVI whether_CSW to_TO offer_VVI the_AT new_JJ treatment_NN1 ._. 
</s>
<s>
What_DDQ sort_NN1 of_IO study_NN1 would_VM be_VBI more_RGR helpful_JJ ?_? <p>_NULL 
</s>
<s>
What_DDQ if_CS the_AT trial_NN1 enrolled_VVD ,_, not_XX 100_MC patients_NN2 per_II group_NN1 ,_, but_CCB 1,000_MC patients_NN2 per_II group_NN1 ,_, and_CC observed_VVD the_AT same_DA event_NN1 rates_NN2 as_CSA before_RT ,_, so_CS21 that_CS22 there_EX were_VBDR 200_MC deaths_NN2 in_II the_AT control_NN1 group_NN1 (_( X_ZZ1 =_FO 200/1,000_MF =_FO 0.20_MC )_) and_CC 150_MC deaths_NN2 in_II the_AT treatment_NN1 group_NN1 (_( Y_ZZ1 =_FO 150/1,000_MF =_FO 0.15_MC )_) ._. 
</s>
<s>
Again_RT ,_, the_AT point_NN1 estimate_NN1 of_IO the_AT RRR_NP1 is_VBZ 25%_NNU (_( 1-Y/X_FU =_FO 1_MC1 -_- &lsqb;_( 0.15/0.20_MF &rsqb;_) x_ZZ1 100_MC =_FO 25%_NNU )_) ._. 
</s>
<s>
In_II this_DD1 larger_JJR trial_NN1 ,_, you_PPY might_VM think_VVI that_CST the_AT true_JJ reduction_NN1 in_II risk_NN1 is_VBZ much_RR closer_JJR to_II 25%_NNU and_CC ,_, again_RT ,_, you_PPY would_VM be_VBI right_JJ ;_; the_AT 95%_NNU confidence_NN1 interval_NN1 on_II the_AT RRR_NP1 for_IF this_DD1 set_NN1 of_IO results_NN2 is_VBZ all_DB on_II the_AT positive_JJ side_NN1 of_IO zero_NN1 and_CC runs_VVZ from_II 9%_NNU to_II 41%_NNU ._. <p>_NULL 
</s>
<s>
What_DDQ these_DD2 examples_NN2 show_VV0 is_VBZ that_CST the_AT larger_JJR the_AT sample_NN1 size_NN1 of_IO a_AT1 trial_NN1 ,_, the_AT larger_JJR the_AT number_NN1 of_IO outcome_NN1 events_NN2 ,_, and_CC the_AT greater_JJR our_APPGE confidence_NN1 that_CST the_AT true_JJ relative_JJ risk_NN1 reduction_NN1 (_( or_CC any_DD other_JJ measure_NN1 of_IO efficacy_NN1 )_) is_VBZ close_JJ to_II what_DDQ we_PPIS2 have_VH0 observed_VVN ._. 
</s>
<s>
In_II the_AT second_MD example_NN1 above_RL ,_, the_AT lowest_JJT plausible_JJ value_NN1 for_IF the_AT RRR_NP1 was_VBDZ 9%_NNU and_CC the_AT highest_JJT value_NN1 41%_NNU ._. 
</s>
<s>
The_AT point_NN1 estimate_NN1 --_NN1 in_II this_DD1 case_NN1 25%_NNU --_NN1 is_VBZ the_AT one_MC1 value_NN1 most_RGT likely_JJ to_TO represent_VVI the_AT true_JJ relative_JJ risk_NN1 reduction_NN1 ._. 
</s>
<s>
As_CSA one_PN1 considers_VVZ values_NN2 farther_RRR and_CC farther_RRR from_II the_AT point_NN1 estimate_NN1 ,_, they_PPHS2 become_VV0 less_DAR and_CC less_RGR consistent_JJ with_IW the_AT observed_JJ relative_JJ risk_NN1 reduction_NN1 ._. 
</s>
<s>
By_II the_AT time_NNT1 one_PN1 crosses_VVZ the_AT upper_JJ or_CC lower_JJR boundaries_NN2 of_IO the_AT 95%_NNU confidence_NN1 interval_NN1 ,_, the_AT values_NN2 are_VBR extremely_RR unlikely_JJ to_TO represent_VVI the_AT true_JJ RRR_NP1 ,_, given_VVN the_AT point_NN1 estimate_NN1 (_( that_REX21 is_REX22 ,_, the_AT observed_JJ RRR_NP1 )_) ._. <p>_NULL 
</s>
<s>
Figure_VV0 1_MC1 represents_VVZ the_AT confidence_NN1 intervals_NN2 around_II the_AT point_NN1 estimate_NN1 of_IO a_AT1 relative_JJ risk_NN1 reduction_NN1 of_IO 25%_NNU in_II these_DD2 two_MC examples_NN2 ,_, with_IW a_AT1 risk_NN1 reduction_NN1 of_IO 0_MC representing_VVG no_AT treatment_NN1 effect_NN1 ._. 
</s>
<s>
In_II both_DB2 scenarios_NN2 the_AT point_NN1 estimate_NN1 of_IO the_AT RRR_NP1 is_VBZ 25%_NNU ,_, but_CCB the_AT confidence_NN1 interval_NN1 is_VBZ far_RR narrower_JJR in_II the_AT second_MD scenario_NN1 ._. 
</s>
<s>
<h>_NULL Figure_VV0 1_MC1 :_: Confidence_NN1 Intervals_NN2 Around_II Relative_JJ Risk_NN1 <p>_NULL 
</s>
<s>
It_PPH1 is_VBZ evident_JJ that_CST the_AT larger_JJR the_AT sample_NN1 size_NN1 ,_, the_AT narrower_JJR the_AT confidence_NN1 interval_NN1 ._. 
</s>
<s>
When_RRQ is_VBZ the_AT sample_NN1 size_NN1 big_JJ enough_RR &lsqb;_( 24_MC &rsqb;_) ?_? 
</s>
<s>
In_II a_AT1 "_" positive_JJ "_" study_NN1 --_NN1 a_AT1 study_NN1 in_II which_DDQ the_AT authors_NN2 conclude_VV0 that_CST the_AT treatment_NN1 is_VBZ effective_JJ --_JJ one_PN1 can_VM look_VVI at_II the_AT lower_JJR boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 ._. 
</s>
<s>
In_II the_AT second_MD example_NN1 ,_, this_DD1 lower_JJR boundary_NN1 was_VBDZ +9%_FO ._. 
</s>
<s>
If_CS this_DD1 risk_NN1 reduction_NN1 (_( the_AT lowest_RRT that_DD1 is_VBZ consistent_JJ with_IW the_AT study_NN1 results_NN2 )_) is_VBZ still_RR important_JJ ,_, or_CC "_" clinically_RR significant_JJ ,_, "_" (_( that_REX21 is_REX22 ,_, it_PPH1 is_VBZ large_JJ enough_RR for_IF you_PPY to_TO want_VVI to_TO offer_VVI it_PPH1 to_II your_APPGE patient_NN1 )_) ,_, then_RT the_AT investigators_NN2 have_VH0 enrolled_VVN sufficient_JJ patients_NN2 ._. 
</s>
<s>
If_CS ,_, on_II the_AT other_JJ hand_NN1 ,_, you_PPY do_VD0 not_XX consider_VVI a_AT1 RRR_NP1 of_IO 9%_NNU clinically_RR significant_JJ ,_, then_RT the_AT study_NN1 can_VM not_XX be_VBI considered_VVN definitive_JJ ,_, even_CS21 if_CS22 its_APPGE results_NN2 are_VBR statistically_RR significant_JJ (_( that_REX21 is_REX22 ,_, they_PPHS2 exclude_VV0 a_AT1 risk_NN1 reduction_NN1 of_IO 0_MC )_) ._. 
</s>
<s>
Keep_VV0 in_II mind_NN1 that_CST the_AT probability_NN1 of_IO the_AT true_JJ value_NN1 being_VBG less_RRR that_CST the_AT lower_JJR boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 is_VBZ only_RR 2.5%_FO ,_, and_CC that_CST a_AT1 different_JJ criterion_NN1 for_IF the_AT confidence_NN1 interval_NN1 (_( a_AT1 90%_NNU confidence_NN1 interval_NN1 ,_, for_REX21 instance_REX22 )_) might_VM be_VBI as_CSA or_CC more_RGR appropriate_JJ ._. 
</s>
<s>
The_AT confidence_NN1 interval_NN1 also_RR helps_VVZ us_PPIO2 interpret_VVI "_" negative_JJ "_" studies_NN2 in_II which_DDQ the_AT authors_NN2 have_VH0 concluded_VVN that_CST the_AT experimental_JJ treatment_NN1 is_VBZ no_AT better_JJR than_CSN control_NN1 therapy_NN1 ._. 
</s>
<s>
All_DB we_PPIS2 need_VM do_VDI is_VBZ look_NN1 at_II the_AT upper_JJ boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 ._. 
</s>
<s>
If_CS the_AT RRR_NP1 at_II this_DD1 upper_JJ boundary_NN1 would_VM ,_, if_CS true_JJ ,_, be_VBI clinically_RR important_JJ ,_, the_AT study_NN1 has_VHZ failed_VVN to_TO exclude_VVI an_AT1 important_JJ treatment_NN1 effect_NN1 ._. 
</s>
<s>
In_II the_AT first_MD example_NN1 we_PPIS2 presented_VVD in_II this_DD1 section_NN1 ,_, the_AT upper_JJ boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 was_VBDZ a_AT1 RRR_NP1 of_IO 59%_NNU ._. 
</s>
<s>
Clearly_RR ,_, if_CS this_DD1 represented_VVD the_AT truth_NN1 ,_, the_AT benefit_NN1 of_IO the_AT treatment_NN1 would_VM be_VBI substantial_JJ ,_, and_CC we_PPIS2 would_VM conclude_VVI that_DD1 ,_, although_CS the_AT investigators_NN2 had_VHD failed_VVN to_TO prove_VVI that_DD1 experimental_JJ treatment_NN1 was_VBDZ better_RRR than_CSN placebo_NN1 ,_, they_PPHS2 also_RR had_VHD failed_VVN to_TO prove_VVI that_CST it_PPH1 was_VBDZ not_XX ;_; they_PPHS2 could_VM not_XX exclude_VVI a_AT1 large_JJ ,_, positive_JJ treatment_NN1 effect_NN1 ._. 
</s>
<s>
Once_RR21 again_RR22 the_AT clinician_NN1 must_VM bear_VVI in_II mind_NN1 the_AT privoso_NN1 about_II the_AT arbitrariness_NN1 of_IO the_AT choice_NN1 of_IO 95%_NNU boundaries_NN2 for_IF the_AT confidence_NN1 interval_NN1 ._. 
</s>
<s>
A_AT1 reasonable_JJ alternative_NN1 ,_, a_AT1 90%_NNU confidence_NN1 interval_NN1 ,_, would_VM be_VBI somewhat_RR narrower_JJR ._. <p>_NULL 
</s>
<s>
What_DDQ can_VM the_AT clinician_NN1 do_VDI if_CS the_AT confidence_NN1 interval_NN1 around_II the_AT RRR_NP1 is_VBZ not_XX reported_VVN in_II the_AT article_NN1 ?_? 
</s>
<s>
There_EX are_VBR three_MC approaches_NN2 ,_, and_CC we_PPIS2 present_VV0 them_PPHO2 in_II order_NN1 of_IO increasing_JJ complexity_NN1 ._. 
</s>
<s>
The_AT easiest_JJT approach_NN1 is_VBZ to_TO examine_VVI the_AT p-value_NN1 ._. 
</s>
<s>
If_CS the_AT p-value_NN1 is_VBZ exactly_RR 0.05_MC ,_, then_RT the_AT lower_JJR bound_NN1 of_IO the_AT 95%_NNU confidence_NN1 limit_NN1 for_IF the_AT RRR_NP1 has_VHZ to_TO lie_VVI exactly_RR at_II zero_MC (_( a_AT1 relative_JJ risk_NN1 of_IO 1_MC1 )_) ,_, and_CC you_PPY can_VM not_XX exclude_VVI the_AT possibility_NN1 that_CST the_AT treatment_NN1 has_VHZ no_AT effect_NN1 ._. 
</s>
<s>
As_II the_AT p-value_NN1 decreases_VVZ below_RG 0.05_MC ,_, the_AT lower_JJR bound_NN1 of_IO the_AT 95%_NNU confidence_NN1 limit_NN1 for_IF the_AT RRR_NP1 rises_VVZ above_II zero_MC ._. <p>_NULL 
</s>
<s>
A_AT1 second_MD approach_NN1 ,_, involving_VVG some_DD quick_JJ mental_JJ arithmetic_NN1 or_CC a_AT1 pencil_NN1 and_CC paper_NN1 ,_, can_VM be_VBI used_VVN when_CS the_AT article_NN1 includes_VVZ the_AT value_NN1 for_IF the_AT standard_JJ error_NN1 of_IO the_AT RRR_NP1 (_( or_CC of_IO the_AT relative_JJ risk_NN1 )_) ._. 
</s>
<s>
This_DD1 is_VBZ because_CS the_AT upper_JJ and_CC lower_JJR boundaries_NN2 of_IO the_AT 95%_NNU confidence_NN1 interval_NN1 for_IF a_AT1 RRR_NP1 are_VBR the_AT point_NN1 estimate_NN1 plus_II and_CC minus_NN1 twice_RR this_DD1 standard_JJ error_NN1 ._. <p>_NULL 
</s>
<s>
The_AT third_MD approach_NN1 involves_VVZ calculating_VVG the_AT confidence_NN1 intervals_NN2 yourself_PPX1 &lsqb;_( 5_MC &rsqb;_) or_CC asking_VVG the_AT help_NN1 of_IO someone_PN1 else_RR (_( a_AT1 statistician_NN1 ,_, for_REX21 instance_REX22 )_) to_TO do_VDI so_RR ._. 
</s>
<s>
Once_CS you_PPY obtain_VV0 the_AT confidence_NN1 intervals_NN2 ,_, you_PPY know_VV0 how_RGQ high_JJ and_CC low_RR the_AT RRR_NP1 might_VM be_VBI (_( that_REX21 is_REX22 ,_, you_PPY know_VV0 the_AT precision_NN1 of_IO the_AT estimate_NN1 of_IO the_AT treatment_NN1 effect_NN1 )_) ,_, and_CC can_VM interpret_VVI the_AT results_NN2 as_CSA described_VVN above_RL ._. <p>_NULL 
</s>
<s>
Not_XX all_DB randomized_JJ trials_NN2 have_VH0 dichotomous_JJ outcomes_NN2 ,_, nor_CC should_VM they_PPHS2 ._. 
</s>
<s>
For_REX21 example_REX22 ,_, a_AT1 new_JJ treatment_NN1 for_IF patients_NN2 with_IW chronic_JJ lung_NN1 disease_NN1 may_VM focus_VVI on_II increasing_VVG their_APPGE exercise_NN1 capacity_NN1 ._. 
</s>
<s>
Thus_RR ,_, in_II a_AT1 study_NN1 of_IO respiratory_JJ muscle_NN1 training_NN1 for_IF patients_NN2 with_IW chronic_JJ airflow_NN1 limitation_NN1 ,_, one_MC1 primary_JJ outcome_NN1 measured_VVD how_RGQ far_JJ patients_NN2 could_VM walk_VVI in_II six_MC minutes_NNT2 in_II an_AT1 enclosed_JJ corridor_NN1 &lsqb;_( 25_MC &rsqb;_) ._. 
</s>
<s>
This_DD1 six-minute_JJ walk_NN1 improved_VVN from_II an_AT1 average_NN1 of_IO 406_MC to_II 416_MC meters_NN2 (_( up_II 10_MC meters_NN2 )_) in_II the_AT experimental_JJ group_NN1 receiving_VVG respiratory_JJ muscle_NN1 training_NN1 ,_, and_CC from_II 409_MC to_II 429_MC (_( up_II 20_MC meters_NN2 )_) in_II the_AT control_NN1 group_NN1 ._. 
</s>
<s>
The_AT point_NN1 estimate_NN1 for_IF improvement_NN1 in_II the_AT six-minute_JJ walk_NN1 due_II21 to_II22 respiratory_JJ muscle_NN1 training_NN1 therefore_RR was_VBDZ negative_JJ ,_, at_II -10_MC meters_NN2 (_( or_CC a_AT1 10_MC meter_NN1 difference_NN1 in_II31 favour_II32 of_II33 the_AT control_NN1 group_NN1 )_) ._. <p>_NULL 
</s>
<s>
Here_RL too_RR ,_, you_PPY should_VM look_VVI for_IF the_AT 95%_NNU confidence_NN1 intervals_NN2 around_II this_DD1 difference_NN1 in_II changes_NN2 in_II exercise_NN1 capacity_NN1 and_CC consider_VV0 their_APPGE implications_NN2 ._. 
</s>
<s>
The_AT investigators_NN2 tell_VV0 us_PPIO2 that_CST the_AT lower_JJR boundary_NN1 of_IO the_AT 95%_NNU confidence_NN1 interval_NN1 was_VBDZ -_- 26_MC (_( that_REX21 is_REX22 ,_, the_AT results_NN2 are_VBR consistent_JJ with_IW a_AT1 difference_NN1 of_IO 26_MC meters_NN2 in_II31 favour_II32 of_II33 the_AT control_NN1 treatment_NN1 )_) and_CC the_AT upper_JJ boundary_NN1 was_VBDZ +5_MC meters_NN2 ._. 
</s>
<s>
Even_RR in_II the_AT best_JJT of_IO circumstances_NN2 ,_, adding_VVG 5_MC meters_NN2 to_II the_AT 400_MC recorded_VVD at_II the_AT start_NN1 of_IO the_AT trial_NN1 would_VM not_XX be_VBI important_JJ to_II the_AT patient_NN1 ,_, and_CC this_DD1 result_NN1 effectively_RR excludes_VVZ a_AT1 clinically_RR significant_JJ benefit_NN1 of_IO respiratory_JJ muscle_NN1 training_NN1 as_CSA applied_VVN in_II this_DD1 study_NN1 ._. <p>_NULL 
</s>
<s>
Having_VHG determined_VVN the_AT magnitude_NN1 and_CC precision_NN1 of_IO the_AT treatment_NN1 effect_NN1 ,_, readers_NN2 now_RT can_VM turn_VVI to_II the_AT final_JJ question_NN1 of_IO how_RRQ to_TO apply_VVI the_AT article_NN1 's_GE results_NN2 to_II their_APPGE patients_NN2 and_CC clinical_JJ practice_NN1 ._. 
</s>
<s>
<h>_NULL Will_VM the_AT results_NN2 help_VVI me_PPIO1 in_II caring_VVG for_IF my_APPGE patients_NN2 ?_? <h>_NULL 1_MC1 ._. 
</s>
<s>
Can_VV0 the_AT results_NN2 be_VBI applied_VVN to_II my_APPGE patient_NN1 care_NN1 ?_? <p>_NULL 
</s>
<s>
The_AT first_MD issue_NN1 to_TO address_VVI is_VBZ how_RRQ confident_JJ you_PPY are_VBR that_CST you_PPY can_VM apply_VVI the_AT results_NN2 to_II a_AT1 particular_JJ patient_NN1 or_CC patients_NN2 in_II your_APPGE practice_NN1 ._. 
</s>
<s>
If_CS the_AT patient_NN1 would_VM have_VHI been_VBN enroled_VVN in_II the_AT study_NN1 had_VHD she_PPHS1 been_VBN there_RL --_NN1 that_REX21 is_REX22 ,_, she_PPHS1 meets_VVZ all_DB the_AT inclusion_NN1 criteria_NN2 ,_, and_CC does_VDZ n't_XX violate_VVI any_DD of_IO the_AT exclusion_NN1 criteria_NN2 --_NN1 there_EX is_VBZ little_DA1 question_NN1 that_CST the_AT results_NN2 are_VBR applicable_JJ ._. 
</s>
<s>
If_CS this_DD1 is_VBZ not_XX the_AT case_NN1 ,_, and_CC she_PPHS1 would_VM not_XX have_VHI been_VBN eligible_JJ for_IF the_AT study_NN1 ,_, judgement_NN1 is_VBZ required_VVN ._. 
</s>
<s>
The_AT study_NN1 result_NN1 probably_RR applies_VVZ even_CS21 if_CS22 ,_, for_REX21 example_REX22 ,_, she_PPHS1 was_VBDZ 2_MC years_NNT2 too_RG old_JJ for_IF the_AT study_NN1 ,_, had_VHD more_DAR severe_JJ disease_NN1 ,_, had_VHD previously_RR been_VBN treated_VVN with_IW a_AT1 competing_JJ therapy_NN1 ,_, or_CC had_VHD a_AT1 comorbid_JJ condition_NN1 ._. 
</s>
<s>
A_AT1 better_JJR approach_NN1 than_CSN rigidly_RR applying_VVG the_AT study_NN1 's_GE inclusion_NN1 and_CC exclusion_NN1 criteria_NN2 is_VBZ to_TO ask_VVI whether_CSW there_EX is_VBZ some_DD compelling_JJ reason_NN1 why_RRQ the_AT results_NN2 should_VM not_XX be_VBI applied_VVN to_II the_AT patient_NN1 ._. 
</s>
<s>
A_AT1 compelling_JJ reason_NN1 usually_RR wo_VM n't_XX be_VBI found_VVN ,_, and_CC most_RGT often_RR you_PPY can_VM generalize_VVI the_AT results_NN2 to_II your_APPGE patient_NN1 with_IW confidence_NN1 ._. <p>_NULL 
</s>
<s>
A_AT1 final_JJ issue_NN1 arises_VVZ when_RRQ our_APPGE patient_NN1 fits_VVZ the_AT features_NN2 of_IO a_AT1 subgroup_NN1 of_IO pateints_NN2 in_II the_AT trial_NN1 report_NN1 ._. 
</s>
<s>
In_II articles_NN2 reporting_VVG the_AT results_NN2 of_IO a_AT1 trial_NN1 (_( especially_RR when_CS the_AT treatment_NN1 does_VDZ n't_XX appear_VVI to_TO be_VBI efficacious_JJ for_IF the_AT average_JJ patient_NN1 )_) ,_, the_AT authors_NN2 may_VM have_VHI examined_VVN a_AT1 large_JJ number_NN1 of_IO subgroups_NN2 of_IO patients_NN2 at_II different_JJ stages_NN2 of_IO their_APPGE illness_NN1 ,_, with_IW different_JJ comorbid_JJ conditions_NN2 ,_, with_IW different_JJ ages_NN2 at_II entry_NN1 ,_, and_CC the_AT like_JJ ._. 
</s>
<s>
Quite_RG often_RR these_DD2 subgroup_VV0 analyses_NN2 were_VBDR not_XX planned_VVN ahead_II21 of_II22 time_NNT1 ,_, and_CC the_AT data_NN are_VBR simply_RR "_" dredged_VVD "_" to_TO see_VVI what_DDQ might_VM turn_VVI up_RP ._. 
</s>
<s>
Investigators_NN2 may_VM sometimes_RT over-interpret_VVI these_DD2 "_" data-dependent_JJ "_" analyses_NN2 as_CSA demonstrating_VVG that_CST the_AT treatment_NN1 really_RR has_VHZ a_AT1 different_JJ effect_NN1 in_II a_AT1 subgroup_NN1 of_IO patients_NN2 --_NN1 those_DD2 who_PNQS are_VBR older_JJR or_CC sicker_JJR ,_, for_REX21 instance_REX22 ,_, may_VM be_VBI held_VVN up_RP as_CSA benefitting_VVG substantially_RR more_RRR or_CC less_DAR than_CSN other_JJ subgroups_NN2 of_IO patients_NN2 in_II the_AT trial_NN1 ._. 
</s>
<s>
You_PPY can_VM find_VVI guides_NN2 for_IF deciding_VVG whether_CSW to_TO believe_VVI these_DD2 subgroup_VV0 analyses_NN2 &lsqb;_( 26_MC &rsqb;_) ,_, and_CC we_PPIS2 'll_VM summarize_VVI them_PPHO2 for_IF you_PPY here_RL :_: the_AT treatment_NN1 is_VBZ really_RR likely_JJ to_TO benefit_VVI the_AT subgroup_NN1 more_RRR or_CC less_DAR than_CSN the_AT other_JJ patients_NN2 if_CS the_AT difference_NN1 in_II the_AT effects_NN2 of_IO treatment_NN1 in_II the_AT subgroups_NN2 is_VBZ large_JJ ;_; is_VBZ very_RG unlikely_JJ to_TO occur_VVI by_II chance_NN1 ;_; results_NN2 from_II an_AT1 analysis_NN1 specified_VVN as_II a_AT1 hypothesis_NN1 before_II the_AT study_NN1 began_VVD ;_; was_VBDZ one_MC1 of_IO only_RR a_AT1 very_RG few_DA2 subgroup_NN1 analyses_VVZ that_CST were_VBDR carried_VVN out_RP ;_; and_CC is_VBZ replicated_VVN in_II other_JJ studies_NN2 ._. 
</s>
<s>
To_II the_AT extent_NN1 that_CST the_AT subgroup_NN1 analysis_NN1 fails_VVZ these_DD2 criteria_NN2 ,_, clinicians_NN2 should_VM be_VBI increasingly_RR sceptical_JJ about_II applying_VVG them_PPHO2 to_II their_APPGE patients._NNU <h>_NULL 2_MC ._. 
</s>
<s>
Were_VBDR all_DB clinically_RR important_JJ outcomes_NN2 considered_VVN ?_? <p>_NULL 
</s>
<s>
Treatments_NN2 are_VBR indicated_VVN when_CS they_PPHS2 provide_VV0 important_JJ benefits_NN2 ._. 
</s>
<s>
Demonstrating_VVG that_CST a_AT1 bronchodilator_NN1 produces_VVZ small_JJ increments_NN2 in_II forced_JJ expired_JJ volume_NN1 in_II patients_NN2 with_IW chronic_JJ airflow_NN1 limitation_NN1 ,_, that_CST a_AT1 vasodilator_NN1 improves_VVZ cardiac_JJ output_NN1 in_II heart_NN1 failure_NN1 patients_NN2 ,_, or_CC that_CST a_AT1 lipid-lowering_JJ agent_NN1 improves_VVZ lipid_JJ profiles_NN2 ,_, does_VDZ not_XX necessarily_RR provide_VVI a_AT1 sufficient_JJ reason_NN1 for_IF administering_VVG these_DD2 drugs_NN2 ._. 
</s>
<s>
What_DDQ is_VBZ required_VVN is_VBZ evidence_NN1 that_CST the_AT treatments_NN2 improve_VV0 outcomes_NN2 that_CST are_VBR important_JJ to_II patients_NN2 ,_, such_II21 as_II22 reducing_VVG shortness_NN1 of_IO breath_NN1 during_II the_AT activities_NN2 required_VVN for_IF daily_JJ living_NN1 ,_, avoiding_VVG hospitalization_NN1 for_IF heart_NN1 failure_NN1 ,_, or_CC decreasing_VVG the_AT risk_NN1 of_IO myocardial_JJ infarction_NN1 ._. 
</s>
<s>
We_PPIS2 can_VM consider_VVI forced_JJ expired_JJ volume_NN1 in_II one_MC1 second_NNT1 ,_, cardiac_JJ output_NN1 ,_, and_CC the_AT lipid_JJ profile_NN1 "_" substitute_NN1 endpoints_NN2 "_" ._. 
</s>
<s>
That_REX21 is_REX22 ,_, the_AT authors_NN2 have_VH0 substituted_VVN these_DD2 physiologic_JJ measures_NN2 for_IF the_AT important_JJ outcomes_NN2 (_( shortness_NN1 of_IO breath_NN1 ,_, hospitalization_NN1 ,_, or_CC myocardial_JJ infarction_NN1 )_) ,_, usually_RR because_CS to_TO confirm_VVI benefit_NN1 on_II the_AT latter_DA they_PPHS2 would_VM have_VHI had_VHN to_TO enroll_VVI many_DA2 more_DAR patients_NN2 and_CC followed_VVD them_PPHO2 for_IF far_RG longer_JJR periods_NN2 of_IO time_NNT1 ._. <p>_NULL 
</s>
<s>
A_AT1 dramatic_JJ recent_JJ example_NN1 of_IO the_AT danger_NN1 of_IO substitute_JJ endpoints_NN2 was_VBDZ found_VVN in_II the_AT evaluation_NN1 of_IO the_AT usefulness_NN1 of_IO antiarrhythmic_JJ drugs_NN2 following_VVG myocardial_JJ infarction_NN1 ._. 
</s>
<s>
Because_CS such_DA drugs_NN2 had_VHD been_VBN shown_VVN to_TO reduce_VVI abnormal_JJ ventricular_JJ depolarizations_NN2 (_( the_AT substitute_JJ endpoints_NN2 )_) in_II the_AT short_JJ run_NN1 ,_, it_PPH1 made_VVD sense_NN1 that_CST they_PPHS2 should_VM reduce_VVI the_AT occurrence_NN1 of_IO life-threatening_JJ arrhythmias_NN2 in_II the_AT long_JJ run_NN1 ._. 
</s>
<s>
A_AT1 group_NN1 of_IO investigators_NN2 performed_VVD randomized_JJ trials_NN2 on_II three_MC agents_NN2 (_( encainide_VV0 ,_, flecainide_NN1 and_CC moricizine_NN1 )_) previously_RR shown_VVN to_TO be_VBI effective_JJ in_II suppressing_VVG the_AT substitute_JJ endpoint_NN1 of_IO abnormal_JJ ventricular_JJ depolarizations_NN2 in_BCL21 order_BCL22 to_TO determine_VVI whether_CSW they_PPHS2 reduced_VVD mortality_NN1 in_II patients_NN2 with_IW asymptomatic_JJ or_CC mildly_RR symptomatic_JJ arrhythmias_NN2 following_VVG myocardial_JJ infarction_NN1 ._. 
</s>
<s>
The_AT investigators_NN2 had_VHD to_TO stop_VVI the_AT trials_NN2 when_CS they_PPHS2 discovered_VVD that_DD1 mortality_NN1 was_VBDZ substantially_RR higher_JJR in_II patients_NN2 receiving_VVG antiarrhythmic_JJ treatment_NN1 than_CSN in_II those_DD2 receiving_VVG placebo_NN1 &lsqb;_( 27_MC &rsqb;_) &lsqb;_( 28_MC &rsqb;_) ._. 
</s>
<s>
Clinicians_NN2 relying_VVG on_II the_AT substitute_JJ endpoint_NN1 of_IO arrhythmia_NN1 suppression_NN1 would_VM have_VHI continued_VVN to_TO administer_VVI the_AT three_MC drugs_NN2 to_II the_AT considerable_JJ detriment_NN1 of_IO their_APPGE patients_NN2 ._. <p>_NULL 
</s>
<s>
Even_CS21 when_CS22 investigators_NN2 report_VV0 favourable_JJ effects_NN2 ot_JJ treatment_NN1 on_II one_PN1 clinically_RR important_JJ outcome_NN1 ,_, clinicians_NN2 must_VM take_VVI care_NN1 that_CST there_EX are_VBR no_AT deleterious_JJ effects_NN2 on_II other_JJ outcomes_NN2 ._. 
</s>
<s>
For_REX21 instance_REX22 ,_, as_CSA this_DD1 series_NN was_VBDZ in_II preparation_NN1 the_AT controversy_NN1 continued_VVD over_RP whether_CSW reducing_VVG lipids_NN2 unexpectedly_RR increases_VVZ non-cardiovascular_JJ causes_NN2 of_IO death_NN1 &lsqb;_( 29_MC &rsqb;_) ._. 
</s>
<s>
Cancer_NN1 chemotherapy_NN1 may_VM lengthen_VVI life_NN1 but_CCB decrease_VV0 its_APPGE quality_NN1 ._. 
</s>
<s>
Finally_RR ,_, surgical_JJ trials_NN2 often_RR document_VV0 prolonged_JJ life_NN1 for_IF those_DD2 who_PNQS survive_VV0 the_AT operation_NN1 (_( yielding_VVG higher_JJR 3-year_JJ survival_NN1 in_II those_DD2 receiving_VVG surgery_NN1 )_) ,_, but_CCB an_AT1 immediate_JJ risk_NN1 of_IO dying_VVG during_II or_CC shortly_RR after_II surgery_NN1 ._. 
</s>
<s>
Accordingly_RR ,_, users_NN2 of_IO the_AT reports_NN2 of_IO surgical_JJ trials_NN2 should_VM look_VVI for_IF information_NN1 on_II immediate_JJ and_CC early_JJ mortality_NN1 (_( typically_RR higher_JJR in_II the_AT surgical_JJ group_NN1 )_) in_II31 addition_II32 to_II33 longer-term_JJ results_NN2 ._. <p>_NULL 
</s>
<s>
If_CS the_AT article_NN1 's_GE results_NN2 are_VBR generalizable_JJ to_II your_APPGE patient_NN1 and_CC its_APPGE outcomes_NN2 are_VBR important_JJ ,_, the_AT next_MD question_NN1 concerns_VVZ whether_CSW the_AT probable_JJ treatment_NN1 benefits_NN2 are_VBR worth_II the_AT effort_NN1 that_CST you_PPY and_CC your_APPGE patient_NN1 must_VM put_VVI into_II the_AT enterprise_NN1 ._. 
</s>
<s>
A_ZZ1 25%_NNU reduction_NN1 in_II the_AT risk_NN1 of_IO death_NN1 may_VM sound_VVI quite_RG impressive_JJ ,_, but_CCB its_APPGE impact_NN1 on_II your_APPGE patient_NN1 and_CC practice_NN1 may_VM nevertheless_RR be_VBI minimal_JJ ._. 
</s>
<s>
This_DD1 notion_NN1 is_VBZ illustrated_VVN using_VVG a_AT1 concept_NN1 called_VVN "_" number_NN1 needed_VVD to_TO treat_VVI "_" (_( NNT_NP1 )_) &lsqb;_( 30_MC &rsqb;_) ._. <p>_NULL 
</s>
<s>
The_AT impact_NN1 of_IO a_AT1 treatment_NN1 is_VBZ related_VVN not_XX only_RR to_II its_APPGE relative_JJ risk_NN1 reduction_NN1 ,_, but_CCB also_RR to_II the_AT risk_NN1 of_IO the_AT adverse_JJ outcome_NN1 it_PPH1 is_VBZ designed_VVN to_TO prevent_VVI ._. 
</s>
<s>
Beta_NN1 blockers_NN2 reduce_VV0 the_AT risk_NN1 of_IO death_NN1 following_VVG myocardial_JJ infarction_NN1 by_II approximately_RR 25%_NNU ,_, and_CC this_DD1 RRR_NP1 is_VBZ consistent_JJ across_II subgroups_NN2 ,_, including_II those_DD2 at_II higher_JJR and_CC lower_JJR "_" baseline_NN1 "_" risk_NN1 of_IO recurrence_NN1 and_CC death_NN1 when_CS they_PPHS2 are_VBR untreated_JJ ._. 
</s>
<s>
Table_NN1 3_MC considers_VVZ two_MC patients_NN2 with_IW recent_JJ myocardial_JJ infarctions_NN2 ._. 
</s>
<s>
<h>_NULL Table_NN1 3_MC :_: Two_MC men_NN2 with_IW contrasting_JJ prognoses_NN2 following_VVG myocardial_JJ infarction_NN1 <p>_NULL 
</s>
<s>
If_CS the_AT risk_NN1 of_IO death_NN1 at_II one_MC1 year_NNT1 without_IW therapy_NN1 (_( baseline_NN1 risk_NN1 )_) is_VBZ :_: X_ZZ1 <p>_NULL 
</s>
<s>
First_MD ,_, consider_VV0 a_AT1 40_MC year_NNT1 old_JJ man_NN1 with_IW a_AT1 small_JJ infarct_NN1 ,_, normal_JJ exercise_NN1 capacity_NN1 ,_, and_CC no_AT sign_NN1 of_IO ventricular_JJ arrhythmia_NN1 who_PNQS is_VBZ willing_JJ to_TO stop_VVI smoking_NN1 ,_, begin_VV0 exercising_VVG ,_, lose_VV0 weight_NN1 ,_, and_CC take_VV0 aspirin_NN daily_RR ._. 
</s>
<s>
This_DD1 individual_NN1 's_GE risk_NN1 of_IO death_NN1 in_II the_AT first_MD year_NNT1 after_II infarction_NN1 may_VM be_VBI as_RG low_JJ as_CSA 1%_NNU ._. 
</s>
<s>
Beta_NN1 blockers_NN2 would_VM reduce_VVI this_DD1 risk_NN1 by_II a_AT1 quarter_NN1 ,_, to_II 0.75%_FO ,_, for_IF an_AT1 absolute_JJ risk_NN1 reduction_NN1 of_IO 0.25%_FO or_CC 0.0025_MC ._. 
</s>
<s>
The_AT inverse_NN1 of_IO this_DD1 absolute_JJ risk_NN1 reduction_NN1 (_( that_REX21 is_REX22 ,_, 1_MC1 /_FO absolute_JJ risk_NN1 reduction_NN1 )_) equals_VVZ the_AT number_NN1 of_IO such_DA patients_NN2 we_PPIS2 'd_VM have_VHI to_TO treat_VVI in_BCL21 order_BCL22 to_TO prevent_VVI one_MC1 event_NN1 (_( in_II this_DD1 case_NN1 ,_, to_TO prevent_VVI one_MC1 death_NN1 following_VVG a_AT1 mild_JJ heart_NN1 attack_NN1 in_II a_AT1 low_JJ risk_NN1 patient_NN1 )_) ._. 
</s>
<s>
In_II this_DD1 case_NN1 ,_, we_PPIS2 would_VM have_VHI to_TO treat_VVI 400_MC such_DA patients_NN2 for_IF one_MC1 year_NNT1 to_TO save_VVI a_AT1 single_JJ life_NN1 (_( 1_MC1 /_FO 0.0025_MC =_FO 400_MC )_) ._. 
</s>
<s>
An_AT1 older_JJR man_NN1 with_IW limited_JJ exercise_NN1 capacity_NN1 and_CC frequent_JJ ventricular_JJ extrasystoles_NN2 who_PNQS continues_VVZ to_TO smoke_VVI following_VVG his_APPGE infarction_NN1 may_VM have_VHI a_AT1 risk_NN1 of_IO dying_VVG in_II that_DD1 next_MD year_NNT1 as_RG high_JJ as_CSA 10%_NNU ._. 
</s>
<s>
A_ZZ1 25%_NNU risk_NN1 reduction_NN1 for_IF death_NN1 in_II such_DA a_AT1 high-risk_JJ patient_NN1 generates_VVZ an_AT1 absolute_JJ risk_NN1 reduction_NN1 of_IO 2.5%_FO or_CC 0.025_MC ,_, and_CC we_PPIS2 would_VM have_VHI to_TO treat_VVI only_RR 40_MC such_DA individuals_NN2 for_IF one_MC1 year_NNT1 to_TO save_VVI a_AT1 life_NN1 (_( 1_MC1 /_FO 0.025_MC =_FO 40_MC )_) ._. <p>_NULL 
</s>
<s>
These_DD2 examples_NN2 underscore_VV0 a_AT1 key_JJ element_NN1 of_IO the_AT decision_NN1 to_TO start_VVI therapy_NN1 :_: before_II deciding_VVG on_II treatment_NN1 ,_, we_PPIS2 must_VM consider_VVI our_APPGE patient_NN1 's_GE risk_NN1 of_IO the_AT adverse_JJ event_NN1 if_CS left_JJ untreated_JJ ._. 
</s>
<s>
For_IF any_DD given_JJ RRR_NP1 ,_, the_AT higher_JJR the_AT probability_NN1 that_CST a_AT1 patient_NN1 will_VM experience_VVI an_AT1 adverse_JJ outcome_NN1 if_CS we_PPIS2 do_VD0 n't_XX treat_VVI ,_, the_AT more_RGR likely_RR the_AT patient_NN1 will_VM benefit_VVI from_II treatment_NN1 ,_, and_CC the_AT fewer_DAR such_DA patients_NN2 we_PPIS2 need_VV0 to_TO treat_VVI to_TO prevent_VVI one_MC1 event_NN1 ._. 
</s>
<s>
Thus_RR ,_, both_DB2 patients_NN2 and_CC our_APPGE own_DA clinical_JJ efficiency_NN1 benefit_NN1 when_CS the_AT number_NN1 we_PPIS2 need_VV0 to_TO treat_VVI to_TO prevent_VVI an_AT1 event_NN1 is_VBZ low_JJ ._. <p>_NULL 
</s>
<s>
We_PPIS2 might_VM not_XX hesitate_VVI to_TO treat_VVI even_RR as_RG many_DA2 as_CSA 400_MC patients_NN2 to_TO save_VVI one_MC1 life_NN1 if_CS the_AT treatment_NN1 was_VBDZ cheap_JJ ,_, easy_JJ to_TO apply_VVI and_CC comply_VVI with_IW ,_, and_CC safe_JJ ._. 
</s>
<s>
In_II reality_NN1 ,_, however_RR ,_, treatments_NN2 usually_RR are_VBR expensive_JJ and_CC they_PPHS2 carry_VV0 risks_NN2 ._. 
</s>
<s>
When_CS these_DD2 risks_NN2 or_CC adverse_JJ outcomes_NN2 are_VBR documented_VVN in_II trial_NN1 reports_NN2 ,_, users_NN2 can_VM apply_VVI the_AT number_NN1 needed_VVD to_TO treat_VVI to_TO judge_VVI both_DB2 the_AT relative_JJ benefits_NN2 and_CC costs_NN2 of_IO therapy_NN1 ._. 
</s>
<s>
If_CS ,_, for_REX21 instance_REX22 ,_, beta_NN1 blockers_NN2 cause_VV0 clinically_RR important_JJ fatigue_NN1 in_II 10%_NNU of_IO the_AT patients_NN2 who_PNQS use_VV0 them_PPHO2 ,_, the_AT NNT_NP1 to_TO cause_VVI fatigue_NN1 is_VBZ 1/0.10_MF or_CC 10_MC ._. 
</s>
<s>
This_DD1 is_VBZ shown_VVN in_II Table_NN1 4_MC ,_, where_CS it_PPH1 is_VBZ seen_VVN that_CST a_AT1 policy_NN1 of_IO treating_VVG low-risk_JJ patients_NN2 after_II myocardial_JJ infarction_NN1 (_( NNT_NP1 =_FO 400_MC to_TO prevent_VVI one_MC1 death_NN1 )_) will_VM result_VVI in_II 40_MC being_VBG fatigued_VVN for_IF every_AT1 life_NN1 saved_VVN ._. 
</s>
<s>
On_II the_AT other_JJ hand_NN1 ,_, a_AT1 policy_NN1 of_IO treating_VVG just_RR high-risk_JJ patients_NN2 will_VM result_VVI in_II 4_MC being_VBG fatigued_VVN for_IF every_AT1 life_NN1 saved_VVN ._. 
</s>
<s>
<h>_NULL Table_NN1 4_MC :_: Incorporating_VVG side-effects_NN2 into_II the_AT Number_NN1 Needed_VVD to_TO be_VBI Treated_VVN <p>_NULL 
</s>
<s>
If_CS the_AT risk_NN1 of_IO death_NN1 at_II one_MC1 year_NNT1 without_IW therapy_NN1 (_( baseline_NN1 risk_NN1 )_) is_VBZ :_: X_ZZ1 <p>_NULL 
</s>
<s>
1%_NNU or_CC 0.01_MC <p>_NULL 
</s>
<s>
10%_NNU or_CC 0.10_MC <p>_NULL 
</s>
<s>
And_CC the_AT risk_NN1 of_IO death_NN1 with_IW propranolol_NN1 is_VBZ :_: Y_ZZ1 <p>_NULL 
</s>
<s>
0.01x0.75=_FO 0.0075_MC <p>_NULL 
</s>
<s>
0.10x0.75=_FO 0.075_MC <p>_NULL 
</s>
<s>
Then_RT the_AT Absolute_JJ risk_NN1 reduction_NN1 is_VBZ :_: X_ZZ1 -_- Y_ZZ1 <p>_NULL 
</s>
<s>
0.01-0.0075=0.0025_FO <p>_NULL 
</s>
<s>
0.10-0.075=0.025_FO <p>_NULL 
</s>
<s>
And_CC the_AT Number_NN1 Needed_VVD to_TO be_VBI Treated_VVN to_TO prevent_VVI one_MC1 event_NN1 is_VBZ :_: 1/_FO (_( X_ZZ1 -_- Y_ZZ1 )_) <p>_NULL 
</s>
<s>
1/0.0025_MF =_FO 400_MC <p>_NULL 
</s>
<s>
1/0.025_MF =_FO 40_MC <p>_NULL 
</s>
<s>
And_CC if_CS the_AT incidence_NN1 of_IO clinically_RR important_JJ fatigue_NN1 on_II propranolol_NN1 is_VBZ :_: <p>_NULL 
</s>
<s>
10%_NNU or_CC 0.10_MC <p>_NULL 
</s>
<s>
Then_RT the_AT number_NN1 of_IO fatigued_JJ patients_NN2 per_II life_NN1 saved_VVN is_VBZ :_: <p>_NULL 
</s>
<s>
400x0.1_FO =_FO 40_MC <p>_NULL 
</s>
<s>
40x0.1_FO =_FO 4_MC <p>_NULL 
</s>
<s>
Clinicians_NN2 do_VD0 n't_XX ,_, however_RR ,_, treat_VV0 groups_NN2 of_IO patients_NN2 uniformly_RR ._. 
</s>
<s>
Rather_RR ,_, we_PPIS2 consider_VV0 individual_JJ responses_NN2 and_CC tailor_VV0 our_APPGE therapy_NN1 accordingly_RR ._. 
</s>
<s>
One_MC1 response_NN1 to_II the_AT problem_NN1 of_IO common_JJ ,_, relatively_RR minor_JJ side_NN1 effects_NN2 (_( such_II21 as_II22 fatigue_NN1 )_) is_VBZ to_TO discontinue_VVI therapy_NN1 in_II patients_NN2 suffering_VVG from_II that_DD1 problem_NN1 ._. 
</s>
<s>
If_CS we_PPIS2 think_VV0 of_IO fatigued_JJ low-risk_JJ patients_NN2 as_II a_AT1 group_NN1 ,_, we_PPIS2 would_VM make_VVI 400_MC patients_NN2 fatigued_VVD to_TO save_VVI a_AT1 life_NN1 ,_, a_AT1 trade-off_NN1 that_CST probably_RR would_VM n't_XX be_VBI worth_II it_PPH1 ._. 
</s>
<s>
By_II discontinuing_VVG treatment_NN1 in_II these_DD2 people_NN ,_, we_PPIS2 can_VM treat_VVI the_AT remainder_NN1 without_IW making_VVG anyone_PN1 fatigued_VVD ._. <p>_NULL 
</s>
<s>
We_PPIS2 can_VM not_XX apply_VVI this_DD1 approach_NN1 ,_, however_RR ,_, to_II severe_JJ ,_, episodic_JJ events_NN2 ._. 
</s>
<s>
Examples_NN2 include_VV0 the_AT risk_NN1 of_IO bleeding_VVG in_II patients_NN2 given_VVN anticoagulants_NN2 ,_, thrombolytic_JJ agents_NN2 ,_, or_CC aspirin_NN ,_, or_CC the_AT risk_NN1 of_IO rare_JJ but_CCB devastating_JJ drug_NN1 reactions_NN2 ._. 
</s>
<s>
In_II each_DD1 of_IO these_DD2 examples_NN2 the_AT number_NN1 of_IO adverse_JJ events_NN2 per_II life_NN1 saved_VVN (_( or_CC ,_, if_CS the_AT events_NN2 are_VBR rare_JJ enough_RR ,_, the_AT number_NN1 of_IO lives_NN2 saved_VVN per_II adverse_JJ event_NN1 )_) can_VM provide_VVI a_AT1 compelling_JJ picture_NN1 of_IO the_AT trade_NN1 offs_NN2 associated_VVN with_IW the_AT intervention_NN1 ._. 
</s>
<s>
<h>_NULL Resolution_NN1 of_IO the_AT Scenario_NN1 <p>_NULL 
</s>
<s>
In_II the_AT randomized_JJ trial_NN1 of_IO warfarin_NN1 in_II non-valvular_JJ atrial_JJ fibrillation_NN1 that_CST you_PPY selected_VVN for_IF reading_NN1 ,_, 260_MC patients_NN2 received_VVD warfarin_NN1 and_CC 265_MC received_JJ placebo_NN1 ._. 
</s>
<s>
The_AT results_NN2 are_VBR summarized_VVN in_II Table_NN1 5_MC ._. 
</s>
<s>
<h>_NULL Table_NN1 5_MC :_: Summary_NN1 of_IO the_AT effect_NN1 of_IO warfarin_NN1 therapy_NN1 on_II patients_NN2 with_IW non-valvular_JJ atrial_JJ fibrillation_NN1 <p>_NULL 
</s>
<s>
If_CS the_AT risk_NN1 of_IO stroke_NN1 at_II one_MC1 year_NNT1 without_IW therapy_NN1 (_( baseline_NN1 risk_NN1 )_) is_VBZ :_: X_ZZ1 <p>_NULL 
</s>
<s>
Over_II the_AT next_MD year-and-a-half_MF ,_, just_RR 4_MC of_IO the_AT former_DA (_( 0.9%_FO per_II year_NNT1 )_) ,_, but_CCB 19_MC of_IO the_AT latter_DA (_( 4.3%_FO per_II year_NNT1 )_) suffered_VVD cerebral_JJ infarction_NN1 ._. 
</s>
<s>
Thus_RR ,_, the_AT relative_JJ risk_NN1 reduction_NN1 (_( RRR_NP1 )_) is_VBZ (_( 0.043_MC -_- 0.009_MC )_) /0.043_MF =_FO 79%_NNU ,_, the_AT absolute_JJ risk_NN1 reduction_NN1 is_VBZ 0.043-0.009_MCMC =_FO 0.034_MC ,_, and_CC the_AT number_NN1 needed_VVD to_TO be_VBI treated_VVN to_TO prevent_VVI one_MC1 stroke_NN1 is_VBZ 1/0.034_MF =_FO 29_MC (_( or_CC approximately_RR 30_MC )_) ._. 
</s>
<s>
Applying_VVG confidence_NN1 intervals_NN2 to_II this_DD1 number_NN1 needed_VVD to_TO treat_VVI ,_, the_AT number_NN1 needed_VVD to_TO treat_VVI could_VM be_VBI (_( using_VVG the_AT lower_JJR boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 around_II the_AT RRR_NP1 ,_, which_DDQ was_VBDZ 0.52_MC )_) as_RG great_JJ as_CSA 45_MC ,_, or_CC (_( using_VVG the_AT upper_JJ boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 around_II the_AT RRR_NP1 ,_, which_DDQ was_VBDZ 0.90_MC )_) as_RG few_DA2 as_CSA 17_MC ._. 
</s>
<s>
Now_RT ,_, you_PPY know_VV0 that_DD1 warfarin_NN1 is_VBZ a_AT1 potentially_RR dangerous_JJ drug_NN1 ,_, and_CC that_CST about_RG 1%_NNU of_IO patients_NN2 on_II this_DD1 treatment_NN1 will_VM suffer_VVI clinically_RR important_JJ bleeding_JJ as_II a_AT1 result_NN1 of_IO treatment_NN1 each_DD1 year_NNT1 &lsqb;_( 31_MC &rsqb;_) ._. 
</s>
<s>
Therefore_RR ,_, there_EX will_VM be_VBI one_MC1 bleed_VV0 in_II every_AT1 100_MC treated_JJ patients_NN2 ,_, and_CC if_CS the_AT number_NN1 needed_VVD to_TO treat_VVI to_TO prevent_VVI a_AT1 stroke_NN1 is_VBZ 30_MC ,_, then_RT for_IF every_AT1 3_MC strokes_NN2 prevented_VVD ,_, one_MC1 major_JJ episode_NN1 of_IO bleeding_VVG would_VM occur_VVI ._. 
</s>
<s>
If_CS the_AT lower_JJR boundary_NN1 of_IO the_AT confidence_NN1 interval_NN1 for_IF the_AT benefit_NN1 of_IO oral_JJ anticoagulants_NN2 represents_VVZ the_AT truth_NN1 ,_, the_AT NNT_NP1 is_VBZ 45_MC and_CC for_IF every_AT1 two_MC strokes_NN2 prevented_VVD ,_, one_MC1 would_VM cause_VVI a_AT1 major_JJ bleed_VV0 ;_; if_CS ,_, on_II the_AT other_JJ hand_NN1 ,_, the_AT upper_JJ boundary_NN1 represents_VVZ the_AT truth_NN1 ,_, the_AT NNT_NP1 is_VBZ 26_MC and_CC approximately_RR 4_MC strokes_NN2 would_VM be_VBI prevented_VVN for_IF every_AT1 major_JJ bleeding_JJ episode_NN1 ._. 
</s>
<s>
The_AT true_JJ risk-benefit_JJ ratio_NN1 probably_RR lies_VVZ somewhere_RL between_II these_DD2 extremes_NN2 ,_, closer_RRR to_II that_DD1 asssociated_VVD with_IW the_AT point_NN1 estimate_NN1 ._. <p>_NULL 
</s>
<s>
And_CC what_DDQ about_II the_AT woman_NN1 with_IW lupus_NN1 nephritis_NN1 ,_, whose_DDQGE plight_NN1 ,_, described_VVD in_RR21 Part_RR22 A_ZZ1 of_IO this_DD1 two-part_JJ essay_NN1 ,_, prompted_VVD us_PPIO2 to_TO find_VVI that_DD1 trial_NN1 of_IO adding_VVG plasmapheresis_NN1 to_II a_AT1 regimen_NN1 of_IO prednisone_NN1 and_CC cyclophosphamide_VV0 ?_? 
</s>
<s>
Unfortunately_RR ,_, although_CS plasmapheresis_NN1 did_VDD produce_VVI sharp_RR declines_VVZ in_II the_AT substituted_JJ end-points_NN2 of_IO anti-dsDNA_JJ antibodies_NN2 and_CC cryoprecipitable_JJ immune_JJ complexes_NN2 ,_, the_AT trial_NN1 did_VDD not_XX find_VVI any_DD benefit_NN1 from_II plasmapheresis_NN1 in_II the_AT clinically_RR important_JJ measures_NN2 of_IO renal_JJ failure_NN1 or_CC mortality_NN1 ._. 
</s>
<s>
When_CS a_AT1 careful_JJ statistical_JJ analysis_NN1 of_IO the_AT emerging_JJ data_NN suggested_VVD little_DA1 hope_NN1 of_IO ever_RR showing_VVG clinical_JJ benefit_NN1 ,_, the_AT trial_NN1 was_VBDZ stopped_VVN ._. 
</s>
<s>
<h>_NULL Conclusion_NN1 <p>_NULL 
</s>
<s>
Having_VHG read_VVN the_AT introduction_NN1 to_II this_DD1 series_NN and_CC the_AT two_MC articles_NN2 on_II using_VVG articles_NN2 about_II therapy_NN1 ,_, we_PPIS2 hope_VV0 that_CST you_PPY are_VBR developing_VVG a_AT1 sense_NN1 of_IO how_RRQ to_TO use_VVI the_AT medical_JJ literature_NN1 to_TO resolve_VVI a_AT1 treatment_NN1 decision_NN1 ._. 
</s>
<s>
First_MD ,_, define_VV0 the_AT problem_NN1 clearly_RR ,_, and_CC use_VV0 one_MC1 of_IO a_AT1 number_NN1 of_IO search_NN1 strategies_NN2 to_TO obtain_VVI the_AT best_JJT available_JJ evidence_NN1 ._. 
</s>
<s>
Having_VHG found_VVN an_AT1 article_NN1 relevant_JJ to_II the_AT therapeutic_JJ issue_NN1 ,_, assess_VV0 the_AT quality_NN1 of_IO the_AT evidence_NN1 ._. 
</s>
<s>
To_II the_AT extent_NN1 that_CST the_AT quality_NN1 of_IO the_AT evidence_NN1 is_VBZ poor_JJ ,_, any_DD subsequent_JJ inference_NN1 (_( and_CC the_AT clinical_JJ decision_NN1 it_PPH1 generates_VVZ )_) will_VM be_VBI weakened_VVN ._. 
</s>
<s>
If_CS the_AT quality_NN1 of_IO the_AT evidence_NN1 is_VBZ adequate_JJ ,_, determine_VV0 the_AT range_NN1 within_II which_DDQ the_AT true_JJ treatment_NN1 effect_NN1 likely_JJ falls_NN2 ._. 
</s>
<s>
Then_RT ,_, consider_VV0 the_AT extent_NN1 to_II which_DDQ the_AT results_NN2 are_VBR generalizable_JJ to_II the_AT patient_NN1 at_II hand_NN1 ,_, and_CC whether_CSW the_AT outcomes_NN2 that_CST have_VH0 been_VBN measured_VVN are_VBR important_JJ ._. 
</s>
<s>
If_CS the_AT generalizability_NN1 is_VBZ in_II doubt_NN1 ,_, or_CC the_AT importance_NN1 of_IO the_AT outcomes_NN2 questionable_JJ ,_, support_VV0 for_IF a_AT1 treatment_NN1 recommendation_NN1 will_VM be_VBI weakened_VVN ._. 
</s>
<s>
Finally_RR ,_, by_II taking_VVG into_II account_NN1 the_AT patient_NN1 's_GE risk_NN1 of_IO adverse_JJ events_NN2 ,_, assess_VV0 the_AT likely_JJ results_NN2 of_IO the_AT intervention_NN1 ._. 
</s>
<s>
This_DD1 involves_VVZ a_AT1 balance_NN1 sheet_NN1 looking_VVG at_II the_AT probability_NN1 of_IO benefit_NN1 ,_, and_CC the_AT associated_JJ costs_NN2 (_( including_II monetary_JJ costs_NN2 ,_, and_CC issues_NN2 such_II21 as_II22 inconvenience_NN1 )_) and_CC risks_NN2 ._. 
</s>
<s>
The_AT bottom_JJ line_NN1 of_IO the_AT balance_NN1 sheet_NN1 will_VM guide_VVI your_APPGE treatment_NN1 decision_NN1 ._. <p>_NULL 
</s>
<s>
While_CS this_DD1 may_VM sound_VVI like_II a_AT1 challenging_JJ route_NN1 to_II deciding_VVG on_II treatment_NN1 ,_, it_PPH1 is_VBZ what_DDQ clinicians_NN2 implicitly_RR do_VD0 each_DD1 time_NNT1 they_PPHS2 administer_VV0 therapy_NN1 &lsqb;_( 32_MC &rsqb;_) ._. 
</s>
<s>
Making_VVG the_AT process_NN1 explicit_JJ ,_, and_CC being_VBG able_JK to_TO apply_VVI guidelines_NN2 to_TO help_VVI assess_VVI the_AT strength_NN1 of_IO evidence_NN1 will_VM ,_, we_PPIS2 think_VV0 ,_, result_VV0 in_II better_JJR patient_NN1 care_NN1 ._. <p>_NULL 
</s>
<s>
24_MC ._. 
</s>
<s>
Detsky_JJ AS_CSA ,_, Sackett_NP1 DL_MC ._. 
</s>
<s>
When_RRQ was_VBDZ a_AT1 "_" negative_JJ "_" clinical_JJ trial_NN1 big_JJ enough_RR ?_? 
</s>
<s>
How_RGQ many_DA2 patients_NN2 you_PPY needed_VVN depends_VVZ on_II what_DDQ you_PPY found_VVD When_RRQ was_VBDZ a_AT1 "_" negative_JJ "_" clinical_JJ trial_NN1 big_JJ enough_RR ?_? 
</s>
<s>
How_RGQ many_DA2 patients_NN2 you_PPY needed_VVN depends_VVZ on_II what_DDQ you_PPY found_VVD ._. 
</s>
<s>
Arch_JJ Intern_NN1 Med_VVD 145._MC 709-12_MCMC (_( 1985_MC )_) ._. 
</s>
