<s>
<p>_NULL 
</s>
<s>
There_EX 's_VBZ a_AT1 smart_JJ thing_NN1 you_PPY can_VM do_VDI ,_, too_RR ,_, to_TO prevent_VVI the_AT Yahoo_NN1 !_! 
</s>
<s>
Mail_NN1 spam_NN1 filters_VVZ from_II becoming_VVG a_AT1 problem_NN1 themselves_PPX2 ._. 
</s>
<s>
The_AT filters_NN2 are_VBR good_JJ ,_, but_CCB not_XX perfect_JJ ,_, and_CC they_PPHS2 can_VM catch_VVI a_AT1 message_NN1 (_( newsletters_NN2 in_RR21 particular_RR22 )_) you_PPY do_VD0 want_VVI to_TO receive_VVI now_RT and_CC then_RT ._. <p>_NULL 
</s>
<s>
To_TO make_VVI sure_JJ you_PPY do_VD0 n't_XX have_VHI to_TO go_VVI reading_VVG your_APPGE favorite_JJ newsletters_NN2 in_II the_AT Bulk_NN1 folder_NN1 in_II Yahoo_NP1 !_! 
</s>
<s>
Mail_NN1 ,_, you_PPY can_VM set_VVI up_RP simple_JJ filters_NN2 that_CST keep_VV0 it_PPH1 in_II your_APPGE Inbox_NN1 ,_, no_DDQV31 matter_DDQV32 what_DDQV33 ._. 
</s>
<s>
I_PPIS1 have_VH0 created_VVN such_DA a_AT1 filter_NN1 for_IF the_AT About_II newsletters_NN2 ,_, for_REX21 example_REX22 ._. 
</s>
