<s>
<3271966>_NULL <h>_NULL Know_VV0 how_RRQ to_TO get_VVI along_II21 with_II22 your_APPGE roommate_NN1 ?_? <p>_NULL 
</s>
<s>
One_MC1 of_IO the_AT biggest_JJT worries_NN2 about_II college_NN1 centers_NN2 around_II the_AT roommate_NN1 situation_NN1 ._. 
</s>
<s>
Whether_CSW you_PPY know_VV0 your_APPGE roommate_NN1 from_II before_RT or_CC it_PPH1 's_VBZ somebody_PN1 totally_RR random_JJ there_EX are_VBR always_RR issues_VVZ that_CST arise_VV0 ._. 
</s>
<s>
It_PPH1 's_VBZ best_JJT to_TO have_VHI a_AT1 set_NN1 of_IO rules_NN2 or_CC guidelines_NN2 in_II mind_NN1 from_II the_AT very_JJ beginning_NN1 in_BCL21 order_BCL22 to_TO avoid_VVI major_JJ conflicts_NN2 in_II the_AT future_NN1 ._. 
</s>
<s>
The_AT Aggie_NP1 has_VHZ created_VVN a_AT1 list_NN1 to_TO help_VVI with_IW this_DD1 :_: <p>_NULL 
</s>
<s>
Communication_NN1 The_AT number_NN1 one_MC1 most_RGT important_JJ thing_NN1 is_VBZ to_TO establish_VVI good_JJ communication_NN1 between_II all_DB the_AT roommates_NN2 --_NN1 regardless_RR of_IO the_AT number_NN1 ._. 
</s>
<s>
Doing_VDG that_DD1 from_II the_AT very_JJ beginning_NN1 helps_NN2 make_VVI the_AT situation_NN1 more_RGR comfortable_JJ ._. <p>_NULL 
</s>
<s>
"_" Starting_VVG from_II when_RRQ you_PPY move_VV0 in_RP ,_, really_RR take_VV0 the_AT time_NNT1 to_TO sit_VVI down_RP and_CC set_VVD up_RP some_DD 'rules_NN2 '_GE for_IF your_APPGE room_NN1 ._. 
</s>
<s>
When_CS you_PPY do_VD0 n't_XX know_VVI someone_PN1 and_CC you_PPY live_VV0 with_IW them_PPHO2 ,_, all_RR41 of_RR42 a_RR43 sudden_RR44 ,_, it_PPH1 takes_VVZ some_DD time_NNT1 to_TO become_VVI comfortable_JJ ._. 
</s>
<s>
Really_RR talking_VVG about_II stuff_NN1 helps_VVZ speed_NN1 up_II that_DD1 process_NN1 ,_, "_" said_VVD Deep_RR Singh_NP1 ,_, junior_JJ mechanical_JJ engineering_NN1 major_NN1 and_CC former_DA resident_JJ advisor_NN1 ._. <p>_NULL 
</s>
<s>
For_IF first-years_NNT2 just_RR moving_VVG into_II the_AT dorms_NN2 ,_, this_DD1 is_VBZ a_AT1 key_JJ piece_NN1 of_IO advice_NN1 ._. 
</s>
<s>
And_CC communication_NN1 is_VBZ the_AT ideal_JJ way_NN1 to_TO establish_VVI a_AT1 friendship_NN1 with_IW your_APPGE roommate_NN1 ._. <p>_NULL 
</s>
<s>
Honesty_NN1 In_II31 addition_II32 to_II33 communication_NN1 ,_, honesty_NN1 is_VBZ an_AT1 essential_JJ aspect_NN1 of_IO establishing_VVG a_AT1 good_JJ relationship_NN1 with_IW your_APPGE roommate_NN1 ._. 
</s>
<s>
It_PPH1 's_VBZ important_JJ to_TO get_VVI everything_PN1 out_RP in_II the_AT open_JJ so_CS there_EX are_VBR no_AT surprises_NN2 later_RRR on_RP ._. 
</s>
<s>
This_DD1 also_RR helps_VVZ you_PPY see_VVI who_PNQS you_PPY would_VM be_VBI a_AT1 compatible_JJ roommate_NN1 with_IW ._. <p>_NULL 
</s>
<s>
"_" The_AT most_RGT important_JJ thing_NN1 to_TO consider_VVI when_CS finding_VVG a_AT1 compatible_JJ roommate_NN1 is_VBZ personality_NN1 ._. 
</s>
<s>
Before_II selecting_VVG whom_PNQO you_PPY 'd_VM like_VVI to_TO room_NN1 with_IW ,_, ask_VV0 him_PPHO1 or_CC her_PPHO1 a_AT1 list_NN1 of_IO questions_NN2 to_TO see_VVI if_CSW they_PPHS2 'd_VM be_VBI the_AT right_JJ match_NN1 for_IF you_PPY ,_, "_" said_VVD sophomore_NN1 psychobiology_NN1 major_JJ Manraj_NP1 Garcha_NP1 ._. 
</s>
<s>
"_" Some_DD examples_NN2 of_IO questions_NN2 are_VBR :_: Do_VD0 you_PPY have_VHI pets_NN2 ?_? 
</s>
<s>
Do_VD0 you_PPY party_VVI ?_? 
</s>
<s>
Do_VD0 you_PPY do_VDI drugs_NN2 ?_? 
</s>
<s>
Are_VBR you_PPY a_AT1 vegetarian_NN1 ?_? 
</s>
<s>
Do_VD0 you_PPY listen_VVI to_II Justin_NP1 Bieber_NP1 ?_? 
</s>
<s>
If_CS so_RR ,_, how_RGQ often_RR ?_? 
</s>
<s>
What_DDQ are_VBR your_APPGE pet_NN1 peeves_VVZ ?_? 
</s>
<s>
On_II a_AT1 level_NN1 of_IO one_MC1 to_II ten_MC ,_, how_RRQ clean_JJ are_VBR you_PPY ?_? "_" <p>_NULL 
</s>
<s>
By_II asking_VVG these_DD2 questions_NN2 you_PPY can_VM find_VVI a_AT1 roommate_NN1 who_PNQS shares_VVZ common_JJ interests_NN2 or_CC has_VHZ similar_JJ habits_NN2 ._. <p>_NULL 
</s>
<s>
Flexibility_NN1 <p>_NULL 
</s>
<s>
It_PPH1 's_VBZ also_RR important_JJ to_TO remember_VVI to_TO be_VBI flexible_JJ and_CC open_VVI ._. 
</s>
<s>
No_RGQV31 matter_RGQV32 how_RGQV33 compatible_JJ you_PPY are_VBR as_CSA roommates_NN2 ,_, situations_NN2 do_VD0 arise_VVI --_NN1 it_PPH1 's_VBZ inevitable_JJ ._. 
</s>
<s>
And_CC getting_VVG angry_JJ at_II every_AT1 little_JJ instance_NN1 wo_VM n't_XX help_VVI solve_VVI any_DD problems_NN2 ._. <p>_NULL 
</s>
<s>
"_" I_PPIS1 think_VV0 the_AT most_RGT important_JJ thing_NN1 to_TO remember_VVI when_CS getting_VVG along_RR with_IW your_APPGE roommate_NN1 is_VBZ to_TO be_VBI flexible_JJ and_CC accommodating_VVG to_II the_AT other_JJ person_NN1 's_GE values_NN2 and_CC concerns_NN2 ._. 
</s>
<s>
Allowing_VVG for_IF flexibility_NN1 helps_NN2 broaden_VVI the_AT scope_NN1 for_IF a_AT1 healthy_JJ and_CC friendly_JJ relationship_NN1 with_IW one_PN1 's_GE roommate_NN1 ,_, "_" said_VVD senior_JJ neurobiology_NN1 ,_, physiology_NN1 and_CC behavior_NN1 major_JJ Pooja_NP1 Mehta_NP1 ._. 
</s>
<s>
"_" Solving_VVG a_AT1 conflict_NN1 would_VM be_VBI best_JJT by_II addressing_VVG the_AT issue_NN1 as_CS31 soon_CS32 as_CS33 it_PPH1 arises_VVZ and_CC talking_VVG about_II it_PPH1 one-on-one_MC ._. 
</s>
<s>
Discussing_VVG the_AT problem_NN1 ,_, and_CC figuring_VVG out_RP together_RL what_DDQ the_AT solutions_NN2 to_II the_AT problem_NN1 can_VM be_VBI ,_, really_RR makes_VVZ a_AT1 difference_NN1 in_II the_AT way_NN1 a_AT1 conflict_NN1 gets_VVZ resolved_VVN ._. "_" <p>_NULL 
</s>
<s>
Friendliness_NN1 But_CCB the_AT most_RGT important_JJ thing_NN1 to_TO remember_VVI is_VBZ to_TO try_VVI and_CC become_VVI friends_NN2 with_IW your_APPGE roommate.There_NNU are_VBR a_AT1 number_NN1 of_IO things_NN2 you_PPY can_VM do_VDI to_TO bond_VVI ._. <p>_NULL 
</s>
<s>
"_" Ideally_RR eating_VVG together_RL is_VBZ a_AT1 great_JJ way_NN1 to_TO bond_VVI ._. 
</s>
<s>
No_PN121 one_PN122 wants_VVZ to_TO go_VVI to_II the_AT Dining_NN1 Commons_NN2 (_( DC_NP1 )_) alone_RR so_RG coordinating_JJ times_NNT2 to_TO eat_VVI is_VBZ great_JJ ,_, "_" Singh_NP1 said_VVD ._. <p>_NULL 
</s>
<s>
"_" An_AT1 ideal_JJ way_NN1 to_TO bond_VVI with_IW your_APPGE roommate(s)_NN2 is_VBZ to_TO go_VVI out_RP and_CC spend_VVI some_DD time_NNT1 with_IW them_PPHO2 away_II21 from_II22 home_NN1 ._. 
</s>
<s>
Whether_CSW you_PPY 're_VBR going_VVG to_II the_AT movies_NN2 ,_, buying_VVG groceries_NN2 or_CC grabbing_VVG a_AT1 drink_NN1 at_II a_AT1 local_JJ pub_NN1 --_NN1 it_PPH1 's_VBZ all_DB a_AT1 part_NN1 of_IO the_AT bonding_NN1 process_NN1 ._. 
</s>
<s>
Rather_CS21 than_CS22 simply_RR considering_VVG them_PPHO2 as_CSA just_RR some_DD roommate_NN1 ,_, you_PPY 're_VBR treating_VVG them_PPHO2 as_II a_AT1 friend_NN1 ,_, "_" Garcha_NP1 said_VVD ._. <p>_NULL 
</s>
<s>
There_EX 's_VBZ no_AT need_NN1 to_TO spend_VVI every_AT1 single_JJ waking_NN1 minute_NNT1 with_IW your_APPGE roommate_NN1 ;_; in_II fact_NN1 that_CST 's_VBZ something_PN1 you_PPY should_VM n't_XX do_VDI ,_, but_CCB a_AT1 healthy_JJ relationship_NN1 with_IW your_APPGE roommate_NN1 or_CC roommates_NN2 can_VM infinitely_RR improve_VVI your_APPGE college_NN1 experience_NN1 ._. 
</s>
<s>
<h>_NULL Media_NN Gallery_NN1 <h>_NULL The_AT California_NP1 Aggie_NP1 <p>_NULL 
</s>
<s>
With_IW more_DAR than_CSN 90_MC writers_NN2 ,_, editors_NN2 ,_, copyreaders_NN2 ,_, photographers_NN2 ,_, designers_NN2 ,_, advertising_NN1 representatives_NN2 and_CC sales_NN clerks_NN2 ,_, The_AT California_NP1 Aggie_NP1 is_VBZ an_AT1 entirely_RR student-run_JJ publication_NN1 ._. 
</s>
<s>
It_PPH1 is_VBZ also_RR financially_RR independent_JJ ,_, receiving_VVG no_AT direct_JJ monetary_JJ support_NN1 from_II ASUCD_NP1 or_CC the_AT university_NN1 ,_, aside_II21 from_II22 using_VVG its_APPGE offices_NN2 in_II 25_MC Lower_JJR Freeborn_JJ rent_NN1 free_JJ ._. 
</s>
<s>
The_AT Aggie_NP1 publishes_VVZ Monday_NPD1 through_II Thursday_NPD1 with_IW over_RG 100_MC distribution_NN1 points_NN2 placed_VVN over_II the_AT UC_NP1 Davis_NP1 campus_NN1 and_CC the_AT city_NN1 of_IO Davis_NP1 ._. 
</s>
<s>
Without_IW a_AT1 journalism_NN1 program_NN1 at_II UC_NP1 Davis_NP1 ,_, The_AT Aggie_NP1 also_RR serves_VVZ as_II a_AT1 valuable_JJ hands-on_JJ laboratory_NN1 for_IF students_NN2 interested_JJ in_II journalism_NN1 ,_, reporting_VVG ,_, opinion_NN1 writing_NN1 and_CC all_DB other_JJ aspects_NN2 of_IO newspaper_NN1 design_NN1 and_CC production_NN1 ._. 
</s>
